export * from './path-utils'
export * from './mailbox'
export * from './messages'
export * from './fs/fs-types'
export * from './fs/fs-utils'
export * from './prettier-utils'
export * from './utopia-vscode-config'
export * from './vscode-communication'
export * from './window-messages'

export const ProjectIDPlaceholderPrefix = 'PLACEHOLDER_DURING_LOADING'
