name: utopia-web
version: 0.1.0.4
synopsis: Utopia Web
description: Utopia Web
github: concrete-utopia/utopia
category: Development
license: MIT
ghc-options: -threaded -rtsopts
dependencies:
  - aeson
  - aeson-pretty
  - amazonka
  - amazonka-core
  - amazonka-s3
  - base >= 4.7 && < 5
  - base16-bytestring
  - binary
  - blaze-html
  - bytestring
  - case-insensitive
  - conduit
  - cookie
  - cryptohash-sha256
  - directory
  - ekg-core
  - ekg-json
  - exceptions
  - filepath
  - free
  - zlib
  - http-api-data
  - http-client
  - http-client-tls
  - http-media
  - http-types
  - generic-lens
  - lens
  - lens-aeson
  - lifted-base
  - mime-types
  - modern-uri
  - monad-control
  - monad-logger
  - mtl
  - network-uri
  - path
  - path-pieces
  - pathwalk
  - persistent <2.10.0
  - persistent-postgresql
  - persistent-sqlite
  - persistent-template
  - process
  - protolude ==0.2.4
  - resource-pool
  - rio
  - servant ==0.15
  - servant-blaze
  - servant-client ==0.15
  - servant-rawm ==0.3.0.0
  - servant-server ==0.15
  - servant-websockets ==1.1.0
  - serversession
  - serversession-backend-persistent
  - split
  - tagsoup
  - tar
  - temporary
  - text
  - time
  - transformers
  - unordered-containers
  - uuid
  - wai
  - wai-app-static
  - wai-extra ==3.0.29.1
  - wai-websockets
  - warp
  - websockets
  - wreq
extra-libraries:
  - z
default-extensions:
  - NoImplicitPrelude
executable:
  main: Main.hs
  source-dirs: src
tests:
  utopia-web-test:
    main: Main.hs
    source-dirs:
      - test
      - src
    dependencies:
      - servant-client-core
      - hspec
      - hedgehog
      - port-utils
      - tasty
      - tasty-hedgehog
      - tasty-hspec
      - tasty-hunit
