name: utopia-web
version: 0.1.1.0
synopsis: Utopia Web
description: Utopia Web
github: concrete-utopia/utopia
category: Development
license: MIT

ghc-options:
  - -Wall
  - -Werror
  - -threaded
  - -fno-warn-orphans
  - -Wno-unused-imports
  - -Wno-deprecations
  - -rtsopts

default-extensions:
  - Strict
  - StrictData
  - NoImplicitPrelude

flags:
  enable-external-tests:
    description: Enable the external tests.
    manual: true
    default: true
dependencies:
  - aeson <2.1
  - aeson-pretty
  - amazonka ==1.6.1
  - amazonka-core ==1.6.1
  - amazonka-s3 ==1.6.1
  - base >= 4.7 && < 5
  - base16-bytestring
  - base64
  - binary
  - blaze-html
  - bytestring
  - case-insensitive
  - cereal
  - concurrent-extra
  - conduit
  - containers
  - cookie
  - cryptohash-sha256
  - cryptonite
  - data-default
  - directory
  - exceptions
  - fast-logger
  - filepath
  - free
  - generic-lens
  - github 
  - hashable
  - hoauth2 ==1.16.0
  - http-api-data
  - http-client
  - http-client-tls
  - http-media
  - http-types
  - JuicyPixels
  - lens
  - lens-aeson <1.2
  - lifted-async
  - lifted-base
  - mime
  - mime-types
  - modern-uri
  - monad-control
  - monad-logger
  - mtl
  - network-uri
  - opaleye
  - opaleye-trans
  - path
  - path-pieces
  - pathwalk
  - postgresql-simple
  - postgresql-simple-migration
  - process
  - product-profunctors
  - protolude ==0.3.0
  - resource-pool
  - rio
  - servant ==0.18.3
  - servant-blaze
  - servant-client ==0.18.3
  - servant-conduit
  - servant-rawm-client
  - servant-rawm-server
  - servant-server ==0.18.3
  - servant-websockets ==2.0.0
  - serversession ==1.0.2
  - split
  - string-conversions
  - tagsoup
  - tar
  - temporary
  - text
  - time
  - time-manager
  - transformers
  - unix
  - unordered-containers
  - uri-bytestring
  - utopia-clientmodel
  - uuid
  - vector
  - wai
  - wai-app-static
  - wai-extra ==3.1.6
  - wai-websockets
  - warp
  - websockets
  - wreq
  - zlib
extra-libraries:
  - z
executable:
  main: Main.hs
  source-dirs: src
tests:
  utopia-web-test:
    when:
    - condition: flag(enable-external-tests)
      then:
        cpp-options: -DENABLE_EXTERNAL_TESTS=True
      else:
        cpp-options: -DENABLE_EXTERNAL_TESTS=False
    main: Main.hs
    ghc-options: +RTS -N1 -RTS
    source-dirs:
      - test
      - src
    dependencies:
      - hedgehog
      - hspec
      - port-utils
      - random
      - servant-client-core
      - tasty
      - tasty-hedgehog
      - tasty-hspec
      - tasty-hunit
