name: utopia-web
version: 0.1.0.4
synopsis: Utopia Web
description: Utopia Web
github: concrete-utopia/utopia
category: Development
license: MIT
ghc-options: -Wall -threaded -rtsopts
dependencies:
  - aeson
  - aeson-pretty
  - amazonka ==1.6.1
  - amazonka-core ==1.6.1
  - amazonka-s3 ==1.6.1
  - base >= 4.7 && < 5
  - base16-bytestring
  - binary
  - blaze-html
  - bytestring
  - case-insensitive
  - cereal
  - concurrent-extra
  - conduit
  - cookie
  - cryptohash-sha256
  - data-default
  - directory
  - ekg-core
  - ekg-json
  - exceptions
  - fast-logger
  - filepath
  - free
  - zlib
  - http-api-data
  - http-client
  - http-client-tls
  - http-media
  - http-types
  - generic-lens
  - lens
  - lens-aeson
  - lifted-base
  - mime-types
  - modern-uri
  - monad-control
  - monad-logger
  - mtl
  - network-uri
  - opaleye
  - opaleye-trans
  - path
  - path-pieces
  - pathwalk
  - postgresql-simple
  - postgresql-simple-migration
  - process
  - product-profunctors
  - protolude ==0.3.0
  - resource-pool
  - rio
  - servant ==0.18.2
  - servant-blaze
  - servant-client ==0.18.2
  - servant-conduit
  - servant-rawm-client
  - servant-rawm-server
  - servant-server ==0.18.2
  - servant-websockets ==2.0.0
  - serversession ==1.0.2
  - split
  - tagsoup
  - tar
  - temporary
  - text
  - time
  - time-manager
  - transformers
  - unix
  - unordered-containers
  - uuid
  - wai
  - wai-app-static
  - wai-extra ==3.0.29.1
  - wai-websockets
  - warp
  - websockets
  - wreq
extra-libraries:
  - z
default-extensions:
  - NoImplicitPrelude
executable:
  main: Main.hs
  source-dirs: src
tests:
  utopia-web-test:
    main: Main.hs
    source-dirs:
      - test
      - src
    dependencies:
      - servant-client-core
      - hspec
      - hedgehog
      - port-utils
      - random
      - tasty
      - tasty-hedgehog
      - tasty-hspec
      - tasty-hunit
