const designRelevantPackages = [
  {
    value: 'react-spring',
    label: 'react-spring',
    contents: [
      'useSpring',
      'useSprings',
      'animated',
      'interpolate',
      'useTrail',
      'useTransition',
      'useChain',
    ],
  },
  { value: 'react-use-gesture', label: 'react-use-gesture', contents: ['useGesture'] },
  {
    value: '@emotion/react',
    label: '@emotion/react',
    contents: ['css', 'jsx', 'Global', 'Classnames'],
  },
  { value: '@emotion/styled', label: '@emotion/styled', contents: ['styled'] },
  { value: '@emotion/css', label: '@emotion/css', contents: ['css'] },
  { value: 'styled-components', label: 'styled-components', contents: ['styled', 'css'] },
  { value: 'leva', label: 'leva', contents: ['useControls'] },
  { value: '@react-three/fiber', label: '@react-three/fiber' },
  { value: '@react-three/drei', label: '@react-three/drei' },
  {
    value: '@react-three/cannon',
    label: '@react-three/cannon',
    contents: [
      'Physics',
      'useBox',
      'usePlane',
      'useCylinder',
      'useHeightfield',
      'useParticle',
      'useSphere',
      'useTrimesh',
      'useConvexPolyhedron',
      'useCompoundBody',
      'usePointToPointConstraint',
      'useConeTwistConstraint',
      'useSpring',
    ],
  },
  { value: 'react-use-measure', label: 'react-use-measure', contents: ['useMeasure'] },
  { value: 'react-laag', label: 'react-laag', contents: ['ToggleLayer'] },
  { value: 'react-router', label: 'react-router' },
  { value: 'tinycolor2', label: 'tinycolor2' },
  { value: 'chroma-js', label: 'chroma-js' },
  { value: 'colors', label: 'colors' },
  { value: 'color', label: 'color' },
  { value: 'd3', label: 'd3' },
  { value: 'font-awesome', label: 'font-awesome' },
]

export const stateManagementPackages = [
  { value: 'zustand', label: 'zustand', contents: ['create'] },
  {
    value: 'immer',
    label: 'immer',
    contents: ['RecoilRoot', 'atom', 'selector', 'useRecoilState', 'useRecoilValue'],
  },
  {
    value: 'recoil',
    label: 'recoil (experimental)',
    contents: ['RecoilRoot', 'atom', 'selector', 'useRecoilState', 'useRecoilValue'],
  },
  {
    value: 'valtio',
    label: 'valtio',
    contents: [
      'proxy',
      'useSnapshot',
      'subscribe',
      'ref',
      'snapshot',
      'addComputed',
      'proxyWithComputed',
    ],
  },
  { value: 'redux', label: 'redux' },
  { value: 'react-redux', label: 'react-redux' },
  { value: 'reselect', label: 'reselect' },
  { value: 'rxjs', label: 'rxjs' },
  { value: 'mobx', label: 'mobx' },
  { value: 'react-router-redux', label: 'react-router-redux' },
  { value: 'redux-saga', label: 'redux-saga' },
  { value: 'flux', label: 'flux' },
]

export const componentLibraryPackages = [
  { value: 'antd', label: 'antd', website: 'https://ant.design/', contents: ['DatePicker'] },
  {
    value: 'semantic-ui',
    label: 'semantic-ui',
    website: 'https://react.semantic-ui.com/usage',
  },
  {
    value: 'fluentui',
    label: 'Fluent UI',
    website: 'https://developer.microsoft.com/en-us/fluentui#/',
    github: 'https://github.com/microsoft/fluentui',
  },

  {
    value: 'blueprintjs',
    label: 'blueprintjs',
    website: 'https://blueprintjs.com/',
    github: 'https://github.com/palantir/blueprint',
  },
  {
    value: 'evergreen',
    label: 'evergreen',
    github: 'https://github.com/segmentio/evergreen',
  },
  {
    value: 'chakra-ui',
    label: 'chakra-ui',
    website: 'https://chakra-ui.com/',
    github: 'https://github.com/chakra-ui/chakra-ui/',
  },
  {
    value: 'rebass',
    label: 'rebass',
    github: 'https://github.com/rebassjs/rebass',
    website: 'https://rebassjs.org/',
  },
  {
    value: 'grommet',
    label: 'grommet',
    website: 'https://grommet.io/',
    github: 'https://github.com/grommet/grommet',
  },
  {
    value: 'rsuite',
    label: 'rsuite',
    website: 'https://rsuitejs.com/',
    github: 'https://github.com/rsuite/rsuite',
  },

  {
    value: 'material-kit-react',
    label: 'material-kit-react',
    website: 'https://github.com/creativetimofficial/material-kit-react/',
    github: 'https://github.com/creativetimofficial/material-kit-react',
  },
  {
    value: 'react-admin',
    label: 'react-admin',
    website: 'https://marmelab.com/react-admin/',
    github: 'https://github.com/marmelab/react-admin',
  },
  {
    value: 'material-ui',
    label: 'material-ui',
    website: 'https://material-ui.com/',
    github: 'https://github.com/mui-org/material-ui/',
  },
  {
    value: 'react-bootstrap',
    label: 'react-bootstrap',
    website: 'https://react-bootstrap.github.io/getting-started/introduction',
    github: 'http://github.com/mui-org/material-ui',
  },
  {
    value: 'react-toolbox',
    label: 'react-toolbox',
    github: 'https://github.com/react-toolbox/react-toolbox',
  },
  {
    value: 'react-onsenui',
    label: 'react-onsenui',
    website: 'https://onsen.io/v2/guide/react/',
  },
]

// First 11 pages of
// https://www.npmjs.com/search?q=react&ranking=optimal&page=1&perPage=20
export const commonReactPackages = [
  { value: 'react-select', label: 'react-select' },
  { value: 'react-draggable', label: 'react-draggable' },
  { value: 'react-popper', label: 'react-popper' },
  { value: 'react-color', label: 'react-color' },
  { value: 'react-table', label: 'react-table' },
  { value: 'react-transition-group', label: 'react-transition-group' },
  { value: 'react-toastify', label: 'react-toastify' },
  { value: 'react-ga', label: 'react-ga' },
  { value: 'rc-util', label: 'rc-util' },
  { value: 'react-router', label: 'react-router' },
  { value: 'react-is', label: 'react-is' },
  { value: 'react-tabs', label: 'react-tabs' },
  { value: 'react-chartjs', label: 'react-chartjs' },
  { value: 'react-hook-form', label: 'react-hook-form' },
  { value: 'downshift', label: 'downshift' },
  { value: 'react-textarea-autosize', label: 'react-textarea-autosize' },
  { value: 'react-measure', label: 'react-measure' },
  { value: 'react-paginate', label: 'react-paginate' },
  { value: 'react-scroll', label: 'react-scroll' },
  { value: 'react-number-format', label: 'react-number-format' },
  { value: 'react-modal', label: 'react-modal' },
  { value: 'react-moment', label: 'react-moment' },
  { value: 'react-motion', label: 'react-motion' },
  { value: 'react-final-form', label: 'react-final-form' },
  { value: 'react-datetime', label: 'react-datetime' },
  { value: 'framer-motion', label: 'framer-motion' },
  { value: 'react-resizable', label: 'react-resizable' },
  { value: 'react-datepicker', label: 'react-datepicker' },
  { value: 'react-tooltip', label: 'react-tooltip' },
  { value: 'react-intl', label: 'react-intl' },
  { value: 'react-i18next', label: 'react-i18next' },
  { value: 'react-icons', label: 'react-icons' },
  { value: 'react-sizeme', label: 'react-sizeme' },
  { value: 'react-image-crop', label: 'react-image-crop' },
  { value: 'react-content-loader', label: 'react-content-loader' },
  { value: 'react-phone-number-input', label: 'react-phone-number-input' },
  { value: 'react-pdf', label: 'react-pdf' },
  { value: 'react-beautiful-dnd', label: 'react-beautiful-dnd' },
  { value: 'react-stripe-elements', label: 'react-stripe-elements' },
  { value: '@stripe/react-stripe-js', label: '@stripe/react-stripe-js' },
  { value: 'react-rnd', label: 'react-rnd' },
  { value: 'react-copy-to-clipboard', label: 'react-copy-to-clipboard' },
  { value: 'react-navigation', label: 'react-navigation' },
  { value: '@testing-library/react-hooks', label: '@testing-library/react-hooks' },
  { value: 'react-dates', label: 'react-dates' },
  { value: 'react-fast-compare', label: 'react-fast-compare' },
  { value: 'rc-slider', label: 'rc-slider' },
  { value: 'react-slick', label: 'react-slick' },
  { value: 're-resizable', label: 're-resizable' },
  { value: 'polished', label: 'polished' },
  { value: 'rc-tooltip', label: 'rc-tooltip' },
  { value: 'react-input-autosize', label: 'react-input-autosize' },
  { value: 'react-cropper', label: 'react-cropper' },
  { value: 'react-autosuggest', label: 'react-autosuggest' },
  { value: 'formik', label: 'formik' },
  { value: 'react-player', label: 'react-player' },
  { value: 'react-parallax', label: 'react-parallax' },
  { value: 'recharts', label: 'recharts' },
  { value: '@fortawesome/react-fontawesome', label: '@fortawesome/react-fontawesome' },
  { value: 'react-timeago', label: 'react-timeago' },
  { value: 'react-slider', label: 'react-slider' },
  { value: 'react-side-effect', label: 'react-side-effect' },
  { value: 'react-calendar', label: 'react-calendar' },
  { value: 'downshift', label: 'downshift' },
  { value: 'react-scroll-up', label: 'react-scroll-up' },
  { value: 'react-window', label: 'react-window' },
  { value: 'react-swipeable', label: 'react-swipeable' },
  { value: 'react-google-login', label: 'react-google-login' },
  { value: 'react-day-picker', label: 'react-day-picker' },
  {
    value: 'react-use',
    label: 'react-use',
    website: 'https://streamich.github.io/react-use/',
    github: 'https://github.com/streamich/react-use/',
  },
  { value: 'sortablejs', label: 'sortablejs' },
  { value: 'react-collapsible', label: 'react-collapsible' },
  { value: 'office-ui-fabric-react', label: 'office-ui-fabric-react' },
  { value: 'react-outside-click-handler', label: 'react-outside-click-handler' },
  { value: 'react-date-picker', label: 'react-date-picker' },
  { value: 'rc-tabs', label: 'rc-tabs' },
  { value: 'react-contenteditable', label: 'react-contenteditable' },
  { value: 'react-with-direction', label: 'react-with-direction' },
  { value: 'react-highlight', label: 'react-highlight' },
  { value: 'react-popper-tooltip', label: 'react-popper-tooltip' },
  { value: 'react-aria-menubutton', label: 'react-aria-menubutton' },
  { value: 'react-grid-layout', label: 'react-grid-layout' },
  { value: 'react-mapbox-gl', label: 'react-mapbox-gl' },
  { value: 'react-dnd', label: 'react-dnd' },
  { value: 'react-date-range', label: 'react-date-range' },
  { value: '@react-google-maps/api', label: '@react-google-maps/api' },
  { value: 'react-lazy-load-image-component', label: 'react-lazy-load-image-component' },
  { value: 'react-resize-detector', label: 'react-resize-detector' },
  { value: 'react-simple-animate', label: 'react-simple-animate' },
  { value: 'rc-tree', label: 'rc-tree' },
  { value: 'google-map-react', label: 'google-map-react' },
  { value: 'react-custom-scroll', label: 'react-custom-scroll' },
  { value: 'rc-menu', label: 'rc-menu' },
  { value: 'rc-dialog', label: 'rc-dialog' },
  { value: 'rc-select', label: 'rc-select' },
  { value: 'react-share', label: 'react-share' },
  { value: '@coreui/react', label: '@coreui/react' },
  { value: 'react-overlays', label: 'react-overlays' },
  {
    value: 'ahooks',
    label: 'ahooks',
    website: 'https://ahooks.js.org/',
  },
]

export const commonUtils = [
  { value: 'lodash', label: 'lodash' },
  { value: 'immutable', label: 'immutable' },
  { value: 'underscore', label: 'underscore' },
  { value: 'ramda', label: 'ramda' },
  { value: 'moment', label: 'moment' },
  { value: 'json5', label: 'json5' },
  {
    value: 'react-virtualized',
    label: 'React Virtualized',
    website: 'https://bvaughn.github.io/react-virtualized/',
    github: 'https://github.com/bvaughn/react-virtualized',
  },
  { value: 'uuid', label: 'uuid' },
  { value: 'url-join', label: 'url-join' },
  { value: 'numeral', label: 'numeral' },
  { value: 'randomstring', label: 'randomstring' },
  { value: 'debounce', label: 'debounce' },
]

export const top1000NPMPackagesOptions = [
  ...designRelevantPackages,
  ...componentLibraryPackages,
  ...commonReactPackages,
  ...stateManagementPackages,
  ...commonUtils,
  { value: 'request', label: 'request' },
  { value: 'chalk', label: 'chalk' },
  { value: 'commander', label: 'commander' },
  { value: 'async', label: 'async' },
  { value: 'react', label: 'react' },
  { value: 'debug', label: 'debug' },
  { value: 'bluebird', label: 'bluebird' },
  { value: 'fs-extra', label: 'fs-extra' },
  { value: 'react-dom', label: 'react-dom' },
  { value: 'mkdirp', label: 'mkdirp' },
  { value: 'prop-types', label: 'prop-types' },
  { value: 'glob', label: 'glob' },
  { value: 'body-parser', label: 'body-parser' },
  { value: 'yargs', label: 'yargs' },
  { value: 'minimist', label: 'minimist' },
  { value: 'yeoman-generator', label: 'yeoman-generator' },
  { value: 'through2', label: 'through2' },
  { value: 'jquery', label: 'jquery' },
  { value: 'babel-runtime', label: 'babel-runtime' },
  { value: 'vue', label: 'vue' },
  { value: 'axios', label: 'axios' },
  { value: 'inquirer', label: 'inquirer' },
  { value: 'babel-core', label: 'babel-core' },
  { value: 'q', label: 'q' },
  { value: 'cheerio', label: 'cheerio' },
  { value: 'classnames', label: 'classnames' },
  { value: 'gulp-util', label: 'gulp-util' },
  { value: 'tslib', label: 'tslib' },
  { value: 'semver', label: 'semver' },
  { value: 'babel-loader', label: 'babel-loader' },
  { value: 'rimraf', label: 'rimraf' },
  { value: 'shelljs', label: 'shelljs' },
  { value: '@angular/core', label: '@angular/core' },
  { value: 'object-assign', label: 'object-assign' },
  { value: 'gulp', label: 'gulp' },
  { value: 'core-js', label: 'core-js' },
  { value: 'zone.js', label: 'zone.js' },
  { value: '@angular/common', label: '@angular/common' },
  { value: 'winston', label: 'winston' },
  { value: 'yosay', label: 'yosay' },
  { value: 'js-yaml', label: 'js-yaml' },
  { value: 'coffee-script', label: 'coffee-script' },
  { value: 'css-loader', label: 'css-loader' },
  { value: 'babel-preset-es2015', label: 'babel-preset-es2015' },
  { value: 'eslint', label: 'eslint' },
  { value: '@angular/platform-browser', label: '@angular/platform-browser' },
  { value: 'socket.io', label: 'socket.io' },
  { value: 'ember-cli-babel', label: 'ember-cli-babel' },
  { value: '@angular/compiler', label: '@angular/compiler' },
  { value: 'handlebars', label: 'handlebars' },
  { value: 'style-loader', label: 'style-loader' },
  { value: 'mocha', label: 'mocha' },
  { value: '@angular/http', label: '@angular/http' },
  { value: '@angular/forms', label: '@angular/forms' },
  {
    value: '@angular/platform-browser-dynamic',
    label: '@angular/platform-browser-dynamic',
  },
  { value: 'babel-polyfill', label: 'babel-polyfill' },
  { value: 'superagent', label: 'superagent' },
  { value: 'ejs', label: 'ejs' },
  { value: 'dotenv', label: 'dotenv' },
  { value: 'optimist', label: 'optimist' },
  { value: '@angular/router', label: '@angular/router' },
  { value: 'mongodb', label: 'mongodb' },
  { value: 'xml2js', label: 'xml2js' },
  { value: 'co', label: 'co' },
  { value: 'aws-sdk', label: 'aws-sdk' },
  { value: 'file-loader', label: 'file-loader' },
  { value: 'ws', label: 'ws' },
  { value: 'babel-eslint', label: 'babel-eslint' },
  { value: 'chai', label: 'chai' },
  { value: 'redis', label: 'redis' },
  { value: 'mongoose', label: 'mongoose' },
  { value: 'typescript', label: 'typescript' },
  { value: 'request-promise', label: 'request-promise' },
  { value: 'path', label: 'path' },

  { value: 'morgan', label: 'morgan' },
  { value: 'promise', label: 'promise' },
  { value: 'ora', label: 'ora' },

  { value: 'node-fetch', label: 'node-fetch' },
  { value: 'autoprefixer', label: 'autoprefixer' },
  { value: 'bootstrap', label: 'bootstrap' },
  { value: 'url-loader', label: 'url-loader' },
  { value: 'webpack-dev-server', label: 'webpack-dev-server' },
  { value: 'node-sass', label: 'node-sass' },
  { value: 'cookie-parser', label: 'cookie-parser' },
  { value: 'eslint-plugin-react', label: 'eslint-plugin-react' },
  { value: 'extend', label: 'extend' },
  { value: 'eslint-plugin-import', label: 'eslint-plugin-import' },
  { value: 'babel-preset-react', label: 'babel-preset-react' },
  { value: 'mime', label: 'mime' },
  { value: 'node-uuid', label: 'node-uuid' },
  { value: 'html-webpack-plugin', label: 'html-webpack-plugin' },
  { value: 'chokidar', label: 'chokidar' },
  { value: 'marked', label: 'marked' },
  { value: 'postcss', label: 'postcss' },
  {
    value: 'extract-text-webpack-plugin',
    label: 'extract-text-webpack-plugin',
  },
  { value: 'less', label: 'less' },
  { value: 'uglify-js', label: 'uglify-js' },
  { value: 'meow', label: 'meow' },
  { value: 'postcss-loader', label: 'postcss-loader' },
  { value: '@types/node', label: '@types/node' },
  { value: '@angular/animations', label: '@angular/animations' },
  { value: 'jade', label: 'jade' },
  { value: 'mysql', label: 'mysql' },
  { value: 'loader-utils', label: 'loader-utils' },
  { value: 'fs', label: 'fs' },

  { value: 'babel-preset-env', label: 'babel-preset-env' },
  { value: 'minimatch', label: 'minimatch' },
  { value: 'es6-promise', label: 'es6-promise' },
  { value: 'qs', label: 'qs' },
  { value: 'whatwg-fetch', label: 'whatwg-fetch' },
  { value: 'joi', label: 'joi' },
  { value: 'underscore.string', label: 'underscore.string' },
  { value: 'babel-cli', label: 'babel-cli' },
  { value: 'prompt', label: 'prompt' },

  { value: 'npm', label: 'npm' },
  { value: 'angular', label: 'angular' },
  { value: 'vue-router', label: 'vue-router' },
  { value: 'socket.io-client', label: 'socket.io-client' },
  { value: 'browserify', label: 'browserify' },
  { value: 'jsonwebtoken', label: 'jsonwebtoken' },
  { value: 'gulp-rename', label: 'gulp-rename' },
  { value: 'eslint-plugin-jsx-a11y', label: 'eslint-plugin-jsx-a11y' },
  { value: 'jest', label: 'jest' },
  { value: 'reflect-metadata', label: 'reflect-metadata' },
  { value: 'del', label: 'del' },
  { value: 'sass-loader', label: 'sass-loader' },
  { value: 'update-notifier', label: 'update-notifier' },
  { value: 'resolve', label: 'resolve' },
  { value: 'nan', label: 'nan' },
  { value: 'xtend', label: 'xtend' },
  { value: 'compression', label: 'compression' },
  { value: 'cross-spawn', label: 'cross-spawn' },
  { value: 'isomorphic-fetch', label: 'isomorphic-fetch' },
  { value: 'koa', label: 'koa' },
  { value: 'grunt', label: 'grunt' },
  { value: 'cors', label: 'cors' },
  { value: 'jsdom', label: 'jsdom' },
  { value: 'ember-cli-htmlbars', label: 'ember-cli-htmlbars' },
  { value: 'react-router-dom', label: 'react-router-dom' },
  { value: 'babel-preset-stage-0', label: 'babel-preset-stage-0' },
  { value: 'express-session', label: 'express-session' },
  { value: 'through', label: 'through' },
  {
    value: 'babel-plugin-transform-runtime',
    label: 'babel-plugin-transform-runtime',
  },
  { value: 'validator', label: 'validator' },
  { value: 'opn', label: 'opn' },
  { value: 'nodemailer', label: 'nodemailer' },
  { value: 'connect', label: 'connect' },
  { value: 'eslint-loader', label: 'eslint-loader' },
  { value: 'babel-jest', label: 'babel-jest' },

  { value: 'inherits', label: 'inherits' },
  { value: 'passport', label: 'passport' },
  { value: 'react-dev-utils', label: 'react-dev-utils' },
  { value: 'redux-thunk', label: 'redux-thunk' },
  { value: 'pg', label: 'pg' },
  { value: 'gulp-uglify', label: 'gulp-uglify' },
  { value: 'eslint-plugin-flowtype', label: 'eslint-plugin-flowtype' },
  { value: 'invariant', label: 'invariant' },
  { value: 'deepmerge', label: 'deepmerge' },
  {
    value: 'case-sensitive-paths-webpack-plugin',
    label: 'case-sensitive-paths-webpack-plugin',
  },
  { value: 'serve-favicon', label: 'serve-favicon' },
  { value: 'readable-stream', label: 'readable-stream' },
  { value: 'open', label: 'open' },
  { value: 'iconv-lite', label: 'iconv-lite' },

  { value: 'got', label: 'got' },
  { value: 'progress', label: 'progress' },

  { value: 'mustache', label: 'mustache' },
  { value: 'bunyan', label: 'bunyan' },
  { value: 'md5', label: 'md5' },
  { value: 'tmp', label: 'tmp' },
  { value: 'webpack-manifest-plugin', label: 'webpack-manifest-plugin' },
  { value: 'babel-register', label: 'babel-register' },
  { value: 'highlight.js', label: 'highlight.js' },
  { value: 'source-map-support', label: 'source-map-support' },
  { value: 'log4js', label: 'log4js' },
  { value: 'cli-table', label: 'cli-table' },
  { value: 'ncp', label: 'ncp' },
  { value: '@babel/runtime', label: '@babel/runtime' },
  { value: 'jsonfile', label: 'jsonfile' },
  { value: 'esprima', label: 'esprima' },
  { value: 'concat-stream', label: 'concat-stream' },
  { value: 'globby', label: 'globby' },
  { value: 'less-loader', label: 'less-loader' },
  { value: 'path-to-regexp', label: 'path-to-regexp' },
  { value: 'stylus', label: 'stylus' },
  { value: 'event-stream', label: 'event-stream' },
  { value: 'babel-preset-react-app', label: 'babel-preset-react-app' },
  { value: 'raf', label: 'raf' },
  { value: 'lru-cache', label: 'lru-cache' },
  { value: '@babel/core', label: '@babel/core' },
  { value: 'postcss-flexbugs-fixes', label: 'postcss-flexbugs-fixes' },
  { value: 'clone', label: 'clone' },
  { value: 'serve-static', label: 'serve-static' },
  { value: 'gulp-concat', label: 'gulp-concat' },
  { value: 'query-string', label: 'query-string' },
  {
    value: 'babel-plugin-transform-object-rest-spread',
    label: 'babel-plugin-transform-object-rest-spread',
  },
  { value: 'graceful-fs', label: 'graceful-fs' },
  { value: 'koa-router', label: 'koa-router' },
  { value: 'crypto', label: 'crypto' },
  { value: 'archiver', label: 'archiver' },
  { value: 'url', label: 'url' },
  { value: 'bindings', label: 'bindings' },
  { value: 'eslint-config-react-app', label: 'eslint-config-react-app' },
  { value: 'cli-color', label: 'cli-color' },
  { value: 'history', label: 'history' },
  { value: 'lodash.merge', label: 'lodash.merge' },
  { value: 'babel', label: 'babel' },
  { value: 'crypto-js', label: 'crypto-js' },
  { value: 'querystring', label: 'querystring' },
  { value: 'http-proxy', label: 'http-proxy' },
  { value: 'config', label: 'config' },
  { value: 'moment-timezone', label: 'moment-timezone' },
  { value: 'pug', label: 'pug' },
  { value: 'json-loader', label: 'json-loader' },
  { value: 'merge', label: 'merge' },
  { value: 'graphql', label: 'graphql' },
  { value: 'ajv', label: 'ajv' },
  { value: 'source-map', label: 'source-map' },
  { value: 'readline-sync', label: 'readline-sync' },
  { value: 'execa', label: 'execa' },
  { value: 'gulp-sourcemaps', label: 'gulp-sourcemaps' },
  { value: 'download-git-repo', label: 'download-git-repo' },
  { value: 'pluralize', label: 'pluralize' },
  { value: 'shortid', label: 'shortid' },
  { value: 'sequelize', label: 'sequelize' },
  { value: 'request-promise-native', label: 'request-promise-native' },
  { value: 'vuex', label: 'vuex' },
  { value: 'browser-sync', label: 'browser-sync' },
  { value: 'when', label: 'when' },
  { value: 'dateformat', label: 'dateformat' },
  { value: 'gulp-sass', label: 'gulp-sass' },
  {
    value: 'babel-plugin-transform-class-properties',
    label: 'babel-plugin-transform-class-properties',
  },
  { value: 'events', label: 'events' },
  { value: 'sqlite3', label: 'sqlite3' },
  { value: 'mime-types', label: 'mime-types' },
  { value: 'js-beautify', label: 'js-beautify' },
  { value: 'nconf', label: 'nconf' },
  { value: 'sw-precache-webpack-plugin', label: 'sw-precache-webpack-plugin' },
  { value: 'sinon', label: 'sinon' },
  { value: 'multer', label: 'multer' },
  { value: 'hoek', label: 'hoek' },
  { value: 'which', label: 'which' },
  { value: 'boom', label: 'boom' },
  { value: 'eslint-config-airbnb', label: 'eslint-config-airbnb' },
  { value: 'figlet', label: 'figlet' },
  { value: 'deep-equal', label: 'deep-equal' },
  { value: 'vinyl', label: 'vinyl' },
  { value: 'ip', label: 'ip' },
  { value: 'fsevents', label: 'fsevents' },
  { value: 'clean-css', label: 'clean-css' },
  {
    value: 'babel-plugin-transform-decorators-legacy',
    label: 'babel-plugin-transform-decorators-legacy',
  },
  { value: 'webpack-dev-middleware', label: 'webpack-dev-middleware' },
  { value: 'temp', label: 'temp' },
  { value: 'util', label: 'util' },
  { value: 'xmldom', label: 'xmldom' },
  { value: 'normalize.css', label: 'normalize.css' },
  { value: 'html-minifier', label: 'html-minifier' },
  { value: 'pify', label: 'pify' },
  { value: 'react-native', label: 'react-native' },
  { value: 'backbone', label: 'backbone' },
  { value: 'tar', label: 'tar' },
  { value: 'eventemitter3', label: 'eventemitter3' },
  { value: 'prettier', label: 'prettier' },
  { value: 'nopt', label: 'nopt' },
  { value: 'warning', label: 'warning' },
  { value: 'webpack-merge', label: 'webpack-merge' },
  { value: 'ini', label: 'ini' },
  { value: 'form-data', label: 'form-data' },
  { value: 'mz', label: 'mz' },
  { value: '@types/lodash', label: '@types/lodash' },
  { value: 'react-hot-loader', label: 'react-hot-loader' },
  { value: 'escodegen', label: 'escodegen' },
  { value: 'webpack-hot-middleware', label: 'webpack-hot-middleware' },

  { value: 'strip-ansi', label: 'strip-ansi' },
  { value: 'markdown-it', label: 'markdown-it' },
  { value: 'react-scripts', label: 'react-scripts' },
  { value: 'run-sequence', label: 'run-sequence' },
  { value: 'command-line-args', label: 'command-line-args' },
  { value: 'unique-random-array', label: 'unique-random-array' },
  { value: 'nunjucks', label: 'nunjucks' },
  { value: 'cross-env', label: 'cross-env' },
  { value: 'passport-local', label: 'passport-local' },
  { value: 'babelify', label: 'babelify' },
  { value: 'puppeteer', label: 'puppeteer' },
  { value: 'bcrypt', label: 'bcrypt' },
  { value: 'hoist-non-react-statics', label: 'hoist-non-react-statics' },
  { value: 'lodash.get', label: 'lodash.get' },
  { value: 'gulp-if', label: 'gulp-if' },
  { value: 'cookie', label: 'cookie' },
  { value: '@babel/preset-env', label: '@babel/preset-env' },
  { value: 'yamljs', label: 'yamljs' },
  { value: 'uglifyjs-webpack-plugin', label: 'uglifyjs-webpack-plugin' },
  { value: 'pkginfo', label: 'pkginfo' },
  { value: 'vinyl-fs', label: 'vinyl-fs' },
  { value: 'should', label: 'should' },
  { value: 'nodemon', label: 'nodemon' },
  { value: 'babel-preset-stage-2', label: 'babel-preset-stage-2' },
  { value: 'recursive-readdir', label: 'recursive-readdir' },
  { value: 'eventemitter2', label: 'eventemitter2' },
  { value: 'bower', label: 'bower' },
  { value: 'vue-template-compiler', label: 'vue-template-compiler' },
  { value: 'dotenv-expand', label: 'dotenv-expand' },
  { value: 'tslint', label: 'tslint' },
  { value: 'koa-static', label: 'koa-static' },
  { value: 'ms', label: 'ms' },
  { value: 'bignumber.js', label: 'bignumber.js' },
  { value: 'react-bootstrap', label: 'react-bootstrap' },
  { value: 'gulp-babel', label: 'gulp-babel' },
  { value: 'htmlparser2', label: 'htmlparser2' },
  { value: 'web3', label: 'web3' },
  { value: 'consolidate', label: 'consolidate' },
  { value: 'gm', label: 'gm' },
  { value: 'gulp-plumber', label: 'gulp-plumber' },
  { value: 'serialport', label: 'serialport' },
  { value: 'assert', label: 'assert' },
  { value: 'github', label: 'github' },
  { value: 'vue-loader', label: 'vue-loader' },
  { value: 'JSONStream', label: 'JSONStream' },
  { value: 'mqtt', label: 'mqtt' },
  { value: 'log-symbols', label: 'log-symbols' },
  { value: 'string', label: 'string' },
  { value: 'method-override', label: 'method-override' },
  { value: 'ioredis', label: 'ioredis' },
  { value: 'hapi', label: 'hapi' },
  { value: '@types/react', label: '@types/react' },
  { value: 'amqplib', label: 'amqplib' },
  { value: 'istanbul', label: 'istanbul' },
  { value: 'copy-webpack-plugin', label: 'copy-webpack-plugin' },
  { value: 'once', label: 'once' },
  { value: 'rsvp', label: 'rsvp' },
  { value: 'lodash.assign', label: 'lodash.assign' },
  { value: 'acorn', label: 'acorn' },
  { value: 'firebase', label: 'firebase' },
  { value: 'lodash.debounce', label: 'lodash.debounce' },
  { value: 'http', label: 'http' },
  { value: 'knex', label: 'knex' },
  { value: 'popper.js', label: 'popper.js' },
  { value: 'babylon', label: 'babylon' },
  { value: 'simple-git', label: 'simple-git' },
  { value: 'systemjs', label: 'systemjs' },
  { value: 'adm-zip', label: 'adm-zip' },
  { value: 'require-dir', label: 'require-dir' },
  { value: 'gulp-autoprefixer', label: 'gulp-autoprefixer' },
  { value: 'tape', label: 'tape' },
  { value: 'ts-loader', label: 'ts-loader' },
  { value: 'date-fns', label: 'date-fns' },
  { value: 'redux-logger', label: 'redux-logger' },
  { value: 'rc', label: 'rc' },
  { value: 'rollup', label: 'rollup' },
  { value: 'node-notifier', label: 'node-notifier' },
  { value: 'html-loader', label: 'html-loader' },
  { value: 'formidable', label: 'formidable' },
  { value: 'deep-extend', label: 'deep-extend' },
  { value: 'recompose', label: 'recompose' },
  { value: 'pump', label: 'pump' },
  { value: 'split', label: 'split' },
  { value: 'wrench', label: 'wrench' },
  { value: 'restify', label: 'restify' },
  { value: 'react-transition-group', label: 'react-transition-group' },
  { value: 'reselect', label: 'reselect' },
  { value: 'walk', label: 'walk' },
  { value: 'global', label: 'global' },
  { value: 'camelcase', label: 'camelcase' },
  { value: 'karma', label: 'karma' },
  { value: 'koa-bodyparser', label: 'koa-bodyparser' },
  { value: 'escape-string-regexp', label: 'escape-string-regexp' },
  {
    value: 'babel-plugin-add-module-exports',
    label: 'babel-plugin-add-module-exports',
  },
  { value: 'helmet', label: 'helmet' },
  { value: 'requirejs', label: 'requirejs' },
  { value: 'http-proxy-middleware', label: 'http-proxy-middleware' },
  { value: 'css', label: 'css' },
  { value: 'element-ui', label: 'element-ui' },
  { value: 'raw-loader', label: 'raw-loader' },
  { value: 'lodash.isequal', label: 'lodash.isequal' },
  { value: 'hammerjs', label: 'hammerjs' },
  { value: 'traverse', label: 'traverse' },
  { value: 'unzip', label: 'unzip' },
  { value: 'app-root-path', label: 'app-root-path' },
  { value: 'download', label: 'download' },
  { value: 'npmlog', label: 'npmlog' },
  { value: 'elasticsearch', label: 'elasticsearch' },
  { value: 'jszip', label: 'jszip' },

  { value: 'rx', label: 'rx' },
  { value: 'sprintf-js', label: 'sprintf-js' },
  { value: 'eslint-plugin-promise', label: 'eslint-plugin-promise' },
  { value: 'library.min.js', label: 'library.min.js' },
  { value: 'broccoli-merge-trees', label: 'broccoli-merge-trees' },
  { value: 'jshint', label: 'jshint' },
  { value: 'create-react-class', label: 'create-react-class' },
  { value: 'argparse', label: 'argparse' },
  { value: 'buffer', label: 'buffer' },
  { value: 'change-case', label: 'change-case' },
  { value: 'lodash.throttle', label: 'lodash.throttle' },
  { value: 'diff', label: 'diff' },
  { value: 'bn.js', label: 'bn.js' },
  { value: 'lodash.clonedeep', label: 'lodash.clonedeep' },
  { value: 'es6-shim', label: 'es6-shim' },
  { value: 'websocket', label: 'websocket' },
  { value: 'cssnano', label: 'cssnano' },
  { value: 'filesize', label: 'filesize' },
  { value: 'gulp-less', label: 'gulp-less' },
  { value: 'ssh2', label: 'ssh2' },

  { value: 'inflection', label: 'inflection' },
  { value: 'co-prompt', label: 'co-prompt' },
  { value: 'swig', label: 'swig' },

  { value: 'mini-css-extract-plugin', label: 'mini-css-extract-plugin' },
  { value: 'babel-types', label: 'babel-types' },
  { value: 'gulp-template', label: 'gulp-template' },
  { value: 'xmlbuilder', label: 'xmlbuilder' },
  { value: 'bcryptjs', label: 'bcryptjs' },
  { value: 'vinyl-source-stream', label: 'vinyl-source-stream' },
  { value: 'cron', label: 'cron' },
  { value: 'plugin-error', label: 'plugin-error' },
  { value: 'react-select', label: 'react-select' },
  { value: '@angular/material', label: '@angular/material' },
  { value: 'js-cookie', label: 'js-cookie' },
  { value: 'escape-html', label: 'escape-html' },
  { value: 'async-validator', label: 'async-validator' },
  { value: 'watch', label: 'watch' },
  {
    value: 'connect-history-api-fallback',
    label: 'connect-history-api-fallback',
  },
  { value: 'gulp-watch', label: 'gulp-watch' },
  { value: 'json-stringify-safe', label: 'json-stringify-safe' },
  { value: 'xmlhttprequest', label: 'xmlhttprequest' },
  { value: 'webpack-cli', label: 'webpack-cli' },
  { value: 'path-exists', label: 'path-exists' },
  { value: 'googleapis', label: 'googleapis' },
  { value: 'send', label: 'send' },
  { value: 'broccoli-funnel', label: 'broccoli-funnel' },
  { value: 'clear', label: 'clear' },
  { value: 'json-stable-stringify', label: 'json-stable-stringify' },
  { value: 'sax', label: 'sax' },
  { value: 'gulp-install', label: 'gulp-install' },
  { value: 'user-home', label: 'user-home' },
  { value: 'nomnom', label: 'nomnom' },
  {
    value: 'optimize-css-assets-webpack-plugin',
    label: 'optimize-css-assets-webpack-plugin',
  },
  { value: 'validate-npm-package-name', label: 'validate-npm-package-name' },
  { value: 'canvas', label: 'canvas' },
  { value: 'get-stdin', label: 'get-stdin' },
  { value: 'jsonschema', label: 'jsonschema' },
  { value: 'metalsmith', label: 'metalsmith' },
  { value: 'oauth', label: 'oauth' },
  { value: 'prettyjson', label: 'prettyjson' },
  { value: 'pull-stream', label: 'pull-stream' },
  { value: 'fs-promise', label: 'fs-promise' },
  { value: 'methods', label: 'methods' },
  { value: 'watchify', label: 'watchify' },
  { value: 'grunt-contrib-clean', label: 'grunt-contrib-clean' },
  { value: 'url-parse', label: 'url-parse' },
  { value: 'postcss-import', label: 'postcss-import' },
  { value: 'errorhandler', label: 'errorhandler' },
  { value: 'grunt-contrib-uglify', label: 'grunt-contrib-uglify' },
  { value: 'ts-node', label: 'ts-node' },
  { value: 'eslint-plugin-standard', label: 'eslint-plugin-standard' },
  { value: 'gulp-replace', label: 'gulp-replace' },
  { value: 'image-size', label: 'image-size' },
  { value: 'configstore', label: 'configstore' },
  { value: 'http-errors', label: 'http-errors' },
  { value: '@angular/cdk', label: '@angular/cdk' },
  { value: 'codemirror', label: 'codemirror' },
  { value: '@babel/polyfill', label: '@babel/polyfill' },
  { value: 'eslint-config-airbnb-base', label: 'eslint-config-airbnb-base' },
  { value: 'estraverse', label: 'estraverse' },
  { value: 'mobx', label: 'mobx' },
  { value: 'liftoff', label: 'liftoff' },
  { value: 'eslint-config-standard', label: 'eslint-config-standard' },
  { value: 'babel-preset-stage-1', label: 'babel-preset-stage-1' },
  { value: 'xlsx', label: 'xlsx' },
  { value: 'safe-buffer', label: 'safe-buffer' },
  { value: 'protobufjs', label: 'protobufjs' },
  { value: 'blessed', label: 'blessed' },
  { value: 'grunt-contrib-watch', label: 'grunt-contrib-watch' },
  { value: 'gulp-conflict', label: 'gulp-conflict' },
  {
    value: 'babel-plugin-transform-es2015-modules-commonjs',
    label: 'babel-plugin-transform-es2015-modules-commonjs',
  },
  { value: 'cli-spinner', label: 'cli-spinner' },
  { value: 'nedb', label: 'nedb' },

  { value: 'cli', label: 'cli' },
  { value: 'leaflet', label: 'leaflet' },
  { value: 'lodash.defaults', label: 'lodash.defaults' },
  { value: 'bs58', label: 'bs58' },
  { value: 'deasync', label: 'deasync' },
  { value: 'clean-webpack-plugin', label: 'clean-webpack-plugin' },
  { value: 'jimp', label: 'jimp' },
  { value: 'three', label: 'three' },
  { value: 'gulp-load-plugins', label: 'gulp-load-plugins' },
  { value: 'eslint-plugin-node', label: 'eslint-plugin-node' },
  { value: 'redux-actions', label: 'redux-actions' },
  { value: 'eslint-config-prettier', label: 'eslint-config-prettier' },
  { value: 'read', label: 'read' },
  { value: 'faker', label: 'faker' },
  { value: 'gulp-imagemin', label: 'gulp-imagemin' },
  { value: 'map-stream', label: 'map-stream' },
  { value: 'portfinder', label: 'portfinder' },
  { value: 'phantomjs', label: 'phantomjs' },
  { value: 'fbjs', label: 'fbjs' },
  {
    value: 'react-addons-css-transition-group',
    label: 'react-addons-css-transition-group',
  },
  { value: '@angular/compiler-cli', label: '@angular/compiler-cli' },
  { value: 'parse5', label: 'parse5' },
  { value: '@types/react-dom', label: '@types/react-dom' },
  { value: 'csv', label: 'csv' },
  { value: 'child_process', label: 'child_process' },
  { value: 'text-table', label: 'text-table' },
  { value: '@babel/preset-react', label: '@babel/preset-react' },
  { value: 'elliptic', label: 'elliptic' },
  { value: 'prismjs', label: 'prismjs' },

  { value: 'level', label: 'level' },
  { value: 'gulp-jshint', label: 'gulp-jshint' },
  { value: 'bytes', label: 'bytes' },
  { value: '@types/express', label: '@types/express' },
  { value: 'phantomjs-prebuilt', label: 'phantomjs-prebuilt' },
  { value: 'object-path', label: 'object-path' },
  { value: 'strip-json-comments', label: 'strip-json-comments' },
  { value: 'node.extend', label: 'node.extend' },
  { value: 'sharp', label: 'sharp' },
  { value: 'node-schedule', label: 'node-schedule' },
  { value: 'graphql-tag', label: 'graphql-tag' },
  { value: 'plist', label: 'plist' },
  { value: 'parseurl', label: 'parseurl' },
  { value: 'electron', label: 'electron' },
  { value: 'react-tap-event-plugin', label: 'react-tap-event-plugin' },
  { value: 'stylelint', label: 'stylelint' },
  { value: 'webpack-bundle-analyzer', label: 'webpack-bundle-analyzer' },
  { value: 'levelup', label: 'levelup' },
  {
    value: '@babel/plugin-proposal-class-properties',
    label: '@babel/plugin-proposal-class-properties',
  },
  { value: 'grunt-contrib-copy', label: 'grunt-contrib-copy' },
  { value: 'grunt-contrib-jshint', label: 'grunt-contrib-jshint' },
  { value: 'gulp-notify', label: 'gulp-notify' },
  { value: 'merge-stream', label: 'merge-stream' },
  { value: 'node-gyp', label: 'node-gyp' },
  { value: 'hiredis', label: 'hiredis' },
  { value: 'brfs', label: 'brfs' },
  { value: 'pm2', label: 'pm2' },
  { value: 'koa-compose', label: 'koa-compose' },
  { value: 'flat', label: 'flat' },
  { value: 'slug', label: 'slug' },
  { value: 'fstream', label: 'fstream' },
  { value: 'gulp-minify-css', label: 'gulp-minify-css' },
  { value: 'mysql2', label: 'mysql2' },
  { value: 'webpack-node-externals', label: 'webpack-node-externals' },
  { value: 'bcrypt-nodejs', label: 'bcrypt-nodejs' },

  { value: 'rollup-plugin-node-resolve', label: 'rollup-plugin-node-resolve' },
  { value: 'sync-request', label: 'sync-request' },
  { value: 'on-finished', label: 'on-finished' },
  { value: 'lodash.isplainobject', label: 'lodash.isplainobject' },
  { value: 'slash', label: 'slash' },
  { value: 'user', label: 'user' },
  { value: 'discord.js', label: 'discord.js' },
  { value: 'vinyl-buffer', label: 'vinyl-buffer' },
  { value: 'babel-traverse', label: 'babel-traverse' },
  { value: 'csv-parse', label: 'csv-parse' },
  { value: 'html-entities', label: 'html-entities' },
  { value: 'lodash.omit', label: 'lodash.omit' },
  { value: 'verror', label: 'verror' },
  {
    value: 'babel-plugin-transform-react-jsx',
    label: 'babel-plugin-transform-react-jsx',
  },
  { value: 'es6-promisify', label: 'es6-promisify' },
  { value: 'micromatch', label: 'micromatch' },
  { value: 'markdown', label: 'markdown' },
  { value: 'clui', label: 'clui' },
  { value: 'connect-redis', label: 'connect-redis' },
  { value: 'throttle-debounce', label: 'throttle-debounce' },
  { value: 'tough-cookie', label: 'tough-cookie' },
  { value: 'find-up', label: 'find-up' },
  { value: 'basic-auth', label: 'basic-auth' },
  { value: 'chart.js', label: 'chart.js' },
  { value: 'unist-util-visit', label: 'unist-util-visit' },
  { value: 'passport-oauth', label: 'passport-oauth' },
  { value: 'karma-chrome-launcher', label: 'karma-chrome-launcher' },
  { value: 'lodash.pick', label: 'lodash.pick' },
  { value: 'webpack-sources', label: 'webpack-sources' },
  { value: 'postcss-cssnext', label: 'postcss-cssnext' },
  { value: 'multimatch', label: 'multimatch' },
  { value: 'detect-port', label: 'detect-port' },
  { value: 'needle', label: 'needle' },
  { value: 'react-helmet', label: 'react-helmet' },
  { value: 'restler', label: 'restler' },
  { value: '@angular/platform-server', label: '@angular/platform-server' },
  { value: 'gaze', label: 'gaze' },
  { value: 'node-emoji', label: 'node-emoji' },
  { value: 'object-hash', label: 'object-hash' },
  { value: 'eslint-plugin-babel', label: 'eslint-plugin-babel' },
  { value: 'osenv', label: 'osenv' },
  { value: 'raw-body', label: 'raw-body' },
  { value: 'extend-shallow', label: 'extend-shallow' },

  { value: 'rollup-plugin-commonjs', label: 'rollup-plugin-commonjs' },
  { value: 'touch', label: 'touch' },
  { value: 'figures', label: 'figures' },
  { value: 'pretty-bytes', label: 'pretty-bytes' },
  { value: 'gulp-filter', label: 'gulp-filter' },
  { value: 'enzyme', label: 'enzyme' },
  { value: 'https', label: 'https' },
  { value: 'valid-url', label: 'valid-url' },
  { value: 'highland', label: 'highland' },
  {
    value: 'babel-plugin-syntax-dynamic-import',
    label: 'babel-plugin-syntax-dynamic-import',
  },
  { value: 'tar-fs', label: 'tar-fs' },
  { value: 'log-update', label: 'log-update' },
  { value: 'supertest', label: 'supertest' },
  { value: 'convert-source-map', label: 'convert-source-map' },
  { value: 'selenium-webdriver', label: 'selenium-webdriver' },
  { value: 'command-line-usage', label: 'command-line-usage' },
  { value: 'shallowequal', label: 'shallowequal' },
  { value: 'eslint-plugin-prettier', label: 'eslint-plugin-prettier' },
  { value: 'requireindex', label: 'requireindex' },
  { value: 'read-pkg-up', label: 'read-pkg-up' },
  { value: 'node-watch', label: 'node-watch' },
  { value: 'finalhandler', label: 'finalhandler' },
  { value: 'path-is-absolute', label: 'path-is-absolute' },
  { value: 'he', label: 'he' },
  {
    value: 'babel-helper-vue-jsx-merge-props',
    label: 'babel-helper-vue-jsx-merge-props',
  },
  { value: 'react-dnd', label: 'react-dnd' },
  { value: 'mobx-react', label: 'mobx-react' },
  { value: 'supports-color', label: 'supports-color' },
  { value: 'node-forge', label: 'node-forge' },
  { value: 'child-process-promise', label: 'child-process-promise' },
  { value: 'readline', label: 'readline' },
  { value: 'draft-js', label: 'draft-js' },
  { value: 'connect-flash', label: 'connect-flash' },

  { value: 'opener', label: 'opener' },
  { value: 'keypress', label: 'keypress' },
  { value: 'mathjs', label: 'mathjs' },
  { value: 'grunt-contrib-concat', label: 'grunt-contrib-concat' },
  { value: 'node-static', label: 'node-static' },
  { value: 'is-plain-object', label: 'is-plain-object' },
  { value: 'grunt-cli', label: 'grunt-cli' },
  { value: 'hogan.js', label: 'hogan.js' },
  { value: 'argv', label: 'argv' },
  { value: 'generic-pool', label: 'generic-pool' },
  { value: 'findup-sync', label: 'findup-sync' },
  { value: 'd3-scale', label: 'd3-scale' },
  { value: 'regenerator-runtime', label: 'regenerator-runtime' },
  { value: 'hyperquest', label: 'hyperquest' },
  { value: 'babel-template', label: 'babel-template' },
  { value: 'gulp-clean-css', label: 'gulp-clean-css' },
  { value: 'lodash.isfunction', label: 'lodash.isfunction' },
  { value: 'assert-plus', label: 'assert-plus' },
  { value: 'cuid', label: 'cuid' },
  { value: 'sprintf', label: 'sprintf' },
  { value: 'install', label: 'install' },
  { value: 'sha1', label: 'sha1' },
  { value: 'passport-oauth2', label: 'passport-oauth2' },
  { value: 'urijs', label: 'urijs' },
  { value: 'urllib', label: 'urllib' },
  { value: 'stylus-loader', label: 'stylus-loader' },
  { value: 'ethereumjs-util', label: 'ethereumjs-util' },
  {
    value: 'babel-plugin-transform-async-to-generator',
    label: 'babel-plugin-transform-async-to-generator',
  },
  { value: 'gulp-postcss', label: 'gulp-postcss' },
  { value: 'bl', label: 'bl' },
  { value: 'lodash-es', label: 'lodash-es' },
  { value: 'babel-generator', label: 'babel-generator' },
  { value: 'fancy-log', label: 'fancy-log' },
  { value: 'component-emitter', label: 'component-emitter' },
  {
    value: 'friendly-errors-webpack-plugin',
    label: 'friendly-errors-webpack-plugin',
  },
  { value: 'stack-trace', label: 'stack-trace' },
  { value: 'identity-obj-proxy', label: 'identity-obj-proxy' },
  { value: 'file-type', label: 'file-type' },
  { value: 'http-server', label: 'http-server' },
  { value: 'utils-merge', label: 'utils-merge' },
  { value: 'crc', label: 'crc' },
  { value: 'node-cache', label: 'node-cache' },
  { value: 'react-intl', label: 'react-intl' },
  { value: 'graphql-tools', label: 'graphql-tools' },
  { value: 'svgo', label: 'svgo' },
  { value: 'chai-as-promised', label: 'chai-as-promised' },
  { value: 'babel-plugin-syntax-jsx', label: 'babel-plugin-syntax-jsx' },
  { value: 'lodash.set', label: 'lodash.set' },
  { value: 'babel-plugin-import', label: 'babel-plugin-import' },
  { value: 'iniparser', label: 'iniparser' },
  { value: 'nodegit', label: 'nodegit' },
  { value: 'require-all', label: 'require-all' },
  { value: 'leveldown', label: 'leveldown' },
  { value: 'lodash.uniq', label: 'lodash.uniq' },
  { value: 'passport-strategy', label: 'passport-strategy' },
  { value: 'jasmine', label: 'jasmine' },
  { value: 'redux-form', label: 'redux-form' },
  { value: 'vorpal', label: 'vorpal' },
  { value: 'nib', label: 'nib' },
  { value: 'node-dir', label: 'node-dir' },
  { value: 'chance', label: 'chance' },
  { value: 'memory-fs', label: 'memory-fs' },
  { value: 'vue-style-loader', label: 'vue-style-loader' },
  { value: 'loglevel', label: 'loglevel' },
  {
    value: 'babel-plugin-transform-regenerator',
    label: 'babel-plugin-transform-regenerator',
  },
  { value: 'recast', label: 'recast' },
  { value: 'gzip-size', label: 'gzip-size' },
  { value: 'babel-preset-stage-3', label: 'babel-preset-stage-3' },
  { value: 'karma-phantomjs-launcher', label: 'karma-phantomjs-launcher' },
  { value: 'depd', label: 'depd' },
  { value: 'xml2json', label: 'xml2json' },
  { value: 'serve-index', label: 'serve-index' },
  { value: 'btoa', label: 'btoa' },
  { value: 'vue-hot-reload-api', label: 'vue-hot-reload-api' },
  { value: 'cli-table2', label: 'cli-table2' },
  { value: '@angular/upgrade', label: '@angular/upgrade' },
  { value: 'lodash.isstring', label: 'lodash.isstring' },

  { value: 'react-dnd-html5-backend', label: 'react-dnd-html5-backend' },
  { value: 'lodash.foreach', label: 'lodash.foreach' },
  { value: 'coveralls', label: 'coveralls' },
  { value: 'type-is', label: 'type-is' },
  { value: 'lodash.template', label: 'lodash.template' },
  { value: 'koa-logger', label: 'koa-logger' },
  { value: 'tildify', label: 'tildify' },
  {
    value: '@babel/plugin-syntax-dynamic-import',
    label: '@babel/plugin-syntax-dynamic-import',
  },
  { value: 'gulp-eslint', label: 'gulp-eslint' },
  { value: 'file-saver', label: 'file-saver' },
  { value: 'sanitize-filename', label: 'sanitize-filename' },
  { value: 'connect-mongo', label: 'connect-mongo' },
  { value: 'accepts', label: 'accepts' },
  { value: 'phantom', label: 'phantom' },
  { value: 'deep-diff', label: 'deep-diff' },
  { value: 'base-64', label: 'base-64' },

  { value: '@material-ui/core', label: '@material-ui/core' },
  { value: 'imagemin', label: 'imagemin' },
  { value: 'etag', label: 'etag' },
  { value: 'npm-run-all', label: 'npm-run-all' },
  { value: 'xregexp', label: 'xregexp' },
  {
    value: '@babel/plugin-transform-runtime',
    label: '@babel/plugin-transform-runtime',
  },
  { value: 'content-type', label: 'content-type' },
  { value: 'mssql', label: 'mssql' },
  { value: 'rollup-plugin-babel', label: 'rollup-plugin-babel' },
  { value: 'copy-paste', label: 'copy-paste' },
  { value: 'react-native-vector-icons', label: 'react-native-vector-icons' },
  { value: 'is-url', label: 'is-url' },
  { value: 'left-pad', label: 'left-pad' },
  { value: 'ts-helpers', label: 'ts-helpers' },
  { value: 'js-base64', label: 'js-base64' },
  { value: 'fluent-ffmpeg', label: 'fluent-ffmpeg' },
  { value: 'jwt-simple', label: 'jwt-simple' },
  { value: 'lodash.camelcase', label: 'lodash.camelcase' },
  { value: 'get-port', label: 'get-port' },
  { value: 'mockjs', label: 'mockjs' },
  { value: 'front-matter', label: 'front-matter' },
  { value: 'promise-polyfill', label: 'promise-polyfill' },
  { value: 'gulp-typescript', label: 'gulp-typescript' },
  { value: 'thunkify', label: 'thunkify' },
  { value: 'karma-jasmine', label: 'karma-jasmine' },
  { value: 'dockerode', label: 'dockerode' },
  { value: 'd3-selection', label: 'd3-selection' },
  { value: 'source-map-loader', label: 'source-map-loader' },
  { value: 'argx', label: 'argx' },
  { value: 'angular-animate', label: 'angular-animate' },
  { value: 'node-pre-gyp', label: 'node-pre-gyp' },
  { value: 'tv4', label: 'tv4' },
  { value: 'lodash.isempty', label: 'lodash.isempty' },
  { value: 'react-dropzone', label: 'react-dropzone' },
  { value: 'long', label: 'long' },
  { value: 'koa-body', label: 'koa-body' },
  { value: 'inert', label: 'inert' },
  { value: 'lodash.map', label: 'lodash.map' },
  { value: 'dot', label: 'dot' },
  { value: 'gulp-shell', label: 'gulp-shell' },
  { value: 'jasmine-core', label: 'jasmine-core' },
  { value: 'pouchdb', label: 'pouchdb' },
  { value: 'forever', label: 'forever' },
  { value: 'wiredep', label: 'wiredep' },
  { value: 'decompress', label: 'decompress' },
  { value: 'serialize-javascript', label: 'serialize-javascript' },
  { value: 'https-proxy-agent', label: 'https-proxy-agent' },
  { value: 'pinkie-promise', label: 'pinkie-promise' },
  { value: 'create-hash', label: 'create-hash' },
  { value: 'soap', label: 'soap' },
  { value: 'columnify', label: 'columnify' },
  {
    value: '@babel/plugin-proposal-object-rest-spread',
    label: '@babel/plugin-proposal-object-rest-spread',
  },
  { value: 'bson', label: 'bson' },
  {
    value: 'babel-plugin-transform-flow-strip-types',
    label: 'babel-plugin-transform-flow-strip-types',
  },
  { value: 'lodash.isobject', label: 'lodash.isobject' },
  { value: 'mout', label: 'mout' },
  { value: 'xhr', label: 'xhr' },
  { value: 'karma-mocha', label: 'karma-mocha' },

  { value: 'arrify', label: 'arrify' },
  { value: 'gulp-clean', label: 'gulp-clean' },
  { value: 'pretty-error', label: 'pretty-error' },
  { value: 'knox', label: 'knox' },
  {
    value: 'react-addons-shallow-compare',
    label: 'react-addons-shallow-compare',
  },
  { value: 'defaults', label: 'defaults' },
  { value: 'is-promise', label: 'is-promise' },
  { value: 'unirest', label: 'unirest' },
  { value: 'uglify-es', label: 'uglify-es' },
  { value: 'resize-observer-polyfill', label: 'resize-observer-polyfill' },
  { value: 'keycode', label: 'keycode' },
  { value: 'react-test-renderer', label: 'react-test-renderer' },
  { value: 'showdown', label: 'showdown' },
  { value: 'd3-array', label: 'd3-array' },
  { value: 'MD5', label: 'MD5' },
  { value: 'lodash.flatten', label: 'lodash.flatten' },
  { value: 'command-exists', label: 'command-exists' },
  { value: 'rollup-pluginutils', label: 'rollup-pluginutils' },
  { value: 'babel-preset-latest', label: 'babel-preset-latest' },
  { value: 'rc-util', label: 'rc-util' },
  { value: 'tracer', label: 'tracer' },
  { value: 'jsdoc', label: 'jsdoc' },
  { value: 'virtual-dom', label: 'virtual-dom' },
  { value: 'byline', label: 'byline' },
  { value: 'lowdb', label: 'lowdb' },
  { value: 'bootstrap-sass', label: 'bootstrap-sass' },
  { value: 'slush', label: 'slush' },
  { value: 'lazy-cache', label: 'lazy-cache' },
  { value: 'callsite', label: 'callsite' },
  { value: 'tweetnacl', label: 'tweetnacl' },
  {
    value: 'babel-plugin-transform-react-remove-prop-types',
    label: 'babel-plugin-transform-react-remove-prop-types',
  },
  { value: 'fastclick', label: 'fastclick' },
  { value: 'imagemin-pngquant', label: 'imagemin-pngquant' },
  { value: 'busboy', label: 'busboy' },
  { value: 'pngjs', label: 'pngjs' },
  { value: 'gulp-mocha', label: 'gulp-mocha' },
  { value: 'listr', label: 'listr' },
  {
    value: 'babel-plugin-transform-es2015-destructuring',
    label: 'babel-plugin-transform-es2015-destructuring',
  },
  { value: 'grpc', label: 'grpc' },
  { value: 'isobject', label: 'isobject' },
  { value: 'radium', label: 'radium' },
  { value: 'normalize-url', label: 'normalize-url' },

  { value: 'shell-quote', label: 'shell-quote' },
  { value: 'follow-redirects', label: 'follow-redirects' },
  { value: 'deep-assign', label: 'deep-assign' },
  { value: 'nock', label: 'nock' },
  { value: 'jquery-ui', label: 'jquery-ui' },
  { value: 'jwt-decode', label: 'jwt-decode' },
  { value: 'localforage', label: 'localforage' },
  { value: 'nyc', label: 'nyc' },
  { value: 'bufferutil', label: 'bufferutil' },
  { value: 'pegjs', label: 'pegjs' },
  { value: 'process', label: 'process' },
  { value: 'es6-error', label: 'es6-error' },
  { value: 'mv', label: 'mv' },
  { value: 'gulp-changed', label: 'gulp-changed' },
  { value: 'standard', label: 'standard' },
  { value: 'split2', label: 'split2' },
  { value: 'preact', label: 'preact' },
  { value: 'jshint-stylish', label: 'jshint-stylish' },
  { value: 'vue-resource', label: 'vue-resource' },

  { value: 'stylelint-config-standard', label: 'stylelint-config-standard' },
  { value: 'passport-facebook', label: 'passport-facebook' },
  { value: 'immutability-helper', label: 'immutability-helper' },
  { value: 'xpath', label: 'xpath' },
  { value: 'react-error-overlay', label: 'react-error-overlay' },
  { value: 'angular-ui-router', label: 'angular-ui-router' },
  { value: 'react-addons-test-utils', label: 'react-addons-test-utils' },
  { value: 'inversify', label: 'inversify' },
  { value: 'duplexify', label: 'duplexify' },
  { value: 'extract-zip', label: 'extract-zip' },
  { value: 'wordwrap', label: 'wordwrap' },
  { value: '@polymer/polymer', label: '@polymer/polymer' },
  { value: 'is', label: 'is' },
  { value: 'cookies', label: 'cookies' },
  { value: 'sugar', label: 'sugar' },
  { value: 'angular-sanitize', label: 'angular-sanitize' },
  {
    value: 'babel-plugin-transform-object-assign',
    label: 'babel-plugin-transform-object-assign',
  },
  { value: 'multiparty', label: 'multiparty' },
  { value: 'md5-file', label: 'md5-file' },
  { value: 'nightmare', label: 'nightmare' },
  { value: 'gulp-htmlmin', label: 'gulp-htmlmin' },
  { value: 'koa-mount', label: 'koa-mount' },
  { value: 'tslint-react', label: 'tslint-react' },
  { value: 'twit', label: 'twit' },
  { value: 'zmq', label: 'zmq' },
  { value: 'fresh', label: 'fresh' },
  { value: 'husky', label: 'husky' },
  {
    value: 'babel-plugin-transform-es2015-parameters',
    label: 'babel-plugin-transform-es2015-parameters',
  },
  { value: 'isarray', label: 'isarray' },
  { value: 'karma-coverage', label: 'karma-coverage' },
  { value: 'log', label: 'log' },
  { value: 'natural', label: 'natural' },
  { value: 'pino', label: 'pino' },
  { value: 'pretty-hrtime', label: 'pretty-hrtime' },
  { value: 'os', label: 'os' },

  { value: 'keymirror', label: 'keymirror' },
  { value: 'ansi-styles', label: 'ansi-styles' },
  { value: 'end-of-stream', label: 'end-of-stream' },
  { value: 'rxjs-compat', label: 'rxjs-compat' },
  { value: 'amqp', label: 'amqp' },
  { value: 'decamelize', label: 'decamelize' },
  { value: 'utf-8-validate', label: 'utf-8-validate' },
  { value: 'findit', label: 'findit' },
  { value: 'ts-jest', label: 'ts-jest' },
  { value: 'sinon-chai', label: 'sinon-chai' },
  { value: 'gray-matter', label: 'gray-matter' },
  { value: 'content-disposition', label: 'content-disposition' },
  { value: 'imports-loader', label: 'imports-loader' },
  { value: 'pako', label: 'pako' },
  { value: 'hexlet-pairs', label: 'hexlet-pairs' },
  { value: 'secp256k1', label: 'secp256k1' },
  { value: 'defined', label: 'defined' },
  { value: 'bytebuffer', label: 'bytebuffer' },
  { value: 'amdefine', label: 'amdefine' },
  { value: 'replace', label: 'replace' },

  { value: 'memory-cache', label: 'memory-cache' },
  { value: 'ndarray', label: 'ndarray' },
  { value: 'ua-parser-js', label: 'ua-parser-js' },
  { value: 'awesome-typescript-loader', label: 'awesome-typescript-loader' },
  { value: 'ftp', label: 'ftp' },
  { value: 'object.assign', label: 'object.assign' },
  { value: 'dom-helpers', label: 'dom-helpers' },
  { value: 'retry', label: 'retry' },
  { value: 'raven', label: 'raven' },
  { value: 'winston-daily-rotate-file', label: 'winston-daily-rotate-file' },
  { value: 'strip-bom', label: 'strip-bom' },
  { value: 'sanitize-html', label: 'sanitize-html' },
  { value: 'on-headers', label: 'on-headers' },
  { value: 'node-cmd', label: 'node-cmd' },
  { value: 'i', label: 'i' },
  { value: 'tiny-lr', label: 'tiny-lr' },
  { value: 'require-directory', label: 'require-directory' },
  { value: 'intl', label: 'intl' },
  { value: 'ecstatic', label: 'ecstatic' },
  { value: 'clipboardy', label: 'clipboardy' },
  { value: 'striptags', label: 'striptags' },
  { value: 'archy', label: 'archy' },
  { value: 'postcss-preset-env', label: 'postcss-preset-env' },
  { value: 'lodash.isarray', label: 'lodash.isarray' },
  { value: 'hash-sum', label: 'hash-sum' },
  { value: 'blueimp-md5', label: 'blueimp-md5' },
  { value: 'event-emitter', label: 'event-emitter' },
  { value: 'gh-pages', label: 'gh-pages' },
  { value: 'range-parser', label: 'range-parser' },
  { value: 'base64-js', label: 'base64-js' },
  { value: 'cookie-signature', label: 'cookie-signature' },
  { value: 'yeoman-environment', label: 'yeoman-environment' },
  { value: 'setimmediate', label: 'setimmediate' },
  { value: 'big.js', label: 'big.js' },
  { value: 'merge-descriptors', label: 'merge-descriptors' },
  { value: 'karma-webpack', label: 'karma-webpack' },
  { value: 'grunt-contrib-cssmin', label: 'grunt-contrib-cssmin' },
  { value: 'toml', label: 'toml' },
  { value: 'gulp-rev', label: 'gulp-rev' },
  { value: 'step', label: 'step' },
  { value: '@types/request', label: '@types/request' },
  { value: 'node-rest-client', label: 'node-rest-client' },
  { value: 'falafel', label: 'falafel' },
  { value: 'docopt', label: 'docopt' },
  { value: 'bigi', label: 'bigi' },
  { value: 'envify', label: 'envify' },
  { value: 'find-root', label: 'find-root' },
  { value: 'hbs', label: 'hbs' },
  { value: 'fibers', label: 'fibers' },
  { value: 'noble', label: 'noble' },
  { value: 'common-tags', label: 'common-tags' },
  { value: 'bitcoinjs-lib', label: 'bitcoinjs-lib' },
  { value: 'gulp-git', label: 'gulp-git' },
  { value: 'animate.css', label: 'animate.css' },
  { value: 'flow-bin', label: 'flow-bin' },
  { value: 'xml', label: 'xml' },
  { value: 'ffi', label: 'ffi' },
  { value: '@types/bluebird', label: '@types/bluebird' },
  { value: 'wreck', label: 'wreck' },
  { value: 'ignore', label: 'ignore' },
  { value: 'camel-case', label: 'camel-case' },
  {
    value: 'progress-bar-webpack-plugin',
    label: 'progress-bar-webpack-plugin',
  },
  { value: 'twilio', label: 'twilio' },
  {
    value: 'babel-plugin-module-resolver',
    label: 'babel-plugin-module-resolver',
  },
  { value: 'big-integer', label: 'big-integer' },

  { value: 'koa-send', label: 'koa-send' },
  {
    value: 'babel-plugin-named-asset-import',
    label: 'babel-plugin-named-asset-import',
  },
  { value: 'git-clone', label: 'git-clone' },
  { value: 'express-jwt', label: 'express-jwt' },
  { value: 'make-dir', label: 'make-dir' },
  { value: 'express-handlebars', label: 'express-handlebars' },
  { value: 'd3-shape', label: 'd3-shape' },
  { value: 'word-wrap', label: 'word-wrap' },
  { value: 'randombytes', label: 'randombytes' },
  { value: 'ansi-escapes', label: 'ansi-escapes' },
  { value: 'is-stream', label: 'is-stream' },
  { value: 'boxen', label: 'boxen' },
  { value: 'react-timer-mixin', label: 'react-timer-mixin' },

  { value: '@oclif/config', label: '@oclif/config' },
  { value: 'webpack-stream', label: 'webpack-stream' },
  { value: 'qiniu', label: 'qiniu' },

  // these are added in for fun:
  { value: '@types/chroma-js', label: '@types/chroma-js' },
  { value: 'react-spring', label: 'react-spring' },
]
