services:
  db-test:
    container_name: utopia-remix-db-test
    image: postgres:13 # matching the version in shell.nix
    ports:
      - 54322:5432
    volumes:
      - db-test-data:/var/lib/postgresql/data-local
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  s3-test:
    container_name: utopia-remix-s3-test
    image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z
    command: server /data
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio-data:/data
  minio-init:
    image: minio/mc
    container_name: utopia-remix-minio-init
    depends_on:
      - s3-test
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc config host add myminio http://utopia-remix-s3-test:9000 minioadmin minioadmin; do sleep 1; done &&
      /usr/bin/mc mb myminio/utopia
      exit 0;
      "

volumes:
  db-test-data:
  minio-data:
