var PACKAGER_TIMEOUT = 'PACKAGER_TIMEOUT';
var PACKAGER_NOT_AVAILABLE = 'PACKAGER_NOT_AVAILABLE';
var STILL_PENDING = 'STILL_PENDING';

module.exports.PACKAGER_NOT_AVAILABLE = PACKAGER_NOT_AVAILABLE;
module.exports.PACKAGER_TIMEOUT = PACKAGER_TIMEOUT;
module.exports.STILL_PENDING = STILL_PENDING;
