import type { Linter } from 'eslint'
import { rules as reactPluginRules } from 'eslint-plugin-react'
import { rules as reactHooksPluginRules } from 'eslint-plugin-react-hooks'
import { rules as jsxA11yPluginRules } from 'eslint-plugin-jsx-a11y'
import eslintImportRuleFirst from 'eslint-plugin-import/lib/rules/first'
import eslintImportRuleNoAmd from 'eslint-plugin-import/lib/rules/no-amd'
import eslintImportRuleNoWebpackSyntax from 'eslint-plugin-import/lib/rules/no-webpack-loader-syntax'

const EsLintRecommended: Linter.RulesRecord = {
  // Currently on 6.8.0 ruleset: https://github.com/eslint/eslint/blob/v6.8.0/conf/eslint-recommended.js
  // This requires manually updating on each release. Urgh.
  'constructor-super': 'error',
  'for-direction': 'warn',
  'getter-return': 'warn',
  'no-async-promise-executor': 'warn',
  'no-case-declarations': 'warn',
  'no-class-assign': 'error',
  'no-compare-neg-zero': 'warn',
  'no-cond-assign': ['warn', 'except-parens'],
  'no-const-assign': 'error',
  'no-constant-condition': 'warn',
  'no-control-regex': 'warn',
  'no-debugger': 'warn',
  'no-delete-var': 'warn',
  'no-dupe-args': 'warn',
  'no-dupe-class-members': 'warn',
  'no-dupe-keys': 'warn',
  'no-duplicate-case': 'warn',
  'no-empty': 'warn',
  'no-empty-character-class': 'warn',
  'no-empty-pattern': 'warn',
  'no-ex-assign': 'warn',
  'no-extra-boolean-cast': 'warn',
  'no-extra-semi': 'warn',
  'no-fallthrough': 'warn',
  'no-func-assign': 'warn',
  'no-global-assign': 'warn',
  'no-inner-declarations': 'warn',
  'no-invalid-regexp': 'warn',
  'no-irregular-whitespace': 'warn',
  'no-misleading-character-class': 'warn',
  'no-mixed-spaces-and-tabs': 'warn',
  'no-new-symbol': 'warn',
  'no-obj-calls': 'warn',
  'no-octal': 'warn',
  'no-prototype-builtins': 'warn',
  'no-redeclare': 'error',
  'no-regex-spaces': 'warn',
  'no-self-assign': 'warn',
  'no-shadow-restricted-names': 'warn',
  'no-sparse-arrays': 'warn',
  'no-this-before-super': 'error',
  'no-undef': 'warn',
  'no-unexpected-multiline': 'warn',
  'no-unreachable': 'warn',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'no-unused-labels': 'warn',
  'no-unused-vars': 'warn',
  'no-useless-catch': 'warn',
  'no-useless-escape': 'warn',
  'no-with': 'error',
  'require-yield': 'warn',
  'use-isnan': 'error',
  'valid-typeof': 'error',
}

export const ESLINT_CONFIG: Linter.Config = {
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
      modules: true,
    },
  },
  env: {
    es2020: true,
    browser: true,
  },
  extends: [], // Not supported in browser - to add these, you have to explicitly add them below
  plugins: [], // plugin rules are loaded using the CustomUtopiaLinter
  globals: {
    __DEV__: false,
    __dirname: false,
    alert: false,
    Blob: false,
    cancelAnimationFrame: false,
    cancelIdleCallback: false,
    clearImmediate: true,
    clearInterval: false,
    clearTimeout: false,
    console: false,
    escape: false,
    Event: false,
    EventTarget: false,
    exports: false,
    fetch: false,
    File: false,
    FileReader: false,
    FormData: false,
    global: false,
    Map: true,
    module: false,
    navigator: false,
    process: false,
    Promise: true,
    requestAnimationFrame: true,
    requestIdleCallback: true,
    require: false,
    Set: true,
    setImmediate: true,
    setInterval: false,
    setTimeout: false,
    WebSocket: false,
    window: false,
    XMLHttpRequest: false,
  },
  rules: {
    ...EsLintRecommended,
    // basic eslint rules
    // http://eslint.org/docs/rules/
    'array-callback-return': 'warn',
    'default-case': ['warn', { commentPattern: '^no default$' }],
    'dot-location': ['warn', 'property'],
    eqeqeq: ['warn', 'smart'],
    'new-parens': 'warn',
    'no-array-constructor': 'warn',
    'no-caller': 'warn',
    'no-eval': 'warn',
    'no-extend-native': 'warn',
    'no-extra-bind': 'warn',
    'no-extra-label': 'warn',
    'no-implied-eval': 'warn',
    'no-iterator': 'warn',
    'no-label-var': 'warn',
    'no-labels': ['warn', { allowLoop: true, allowSwitch: false }],
    'no-lone-blocks': 'warn',
    'no-loop-func': 'warn',
    'no-mixed-operators': [
      'warn',
      {
        groups: [
          ['&', '|', '^', '~', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
          ['&&', '||'],
          ['in', 'instanceof'],
        ],
        allowSamePrecedence: false,
      },
    ],
    'no-multi-str': 'warn',
    'no-native-reassign': 'warn',
    'no-negated-in-lhs': 'warn',
    'no-new-func': 'warn',
    'no-new-object': 'warn',
    'no-new-wrappers': 'warn',
    'no-octal-escape': 'warn',
    'no-restricted-syntax': ['warn', 'WithStatement'],
    'no-script-url': 'warn',
    'no-self-compare': 'warn',
    'no-sequences': 'warn',
    'no-template-curly-in-string': 'warn',
    'no-throw-literal': 'warn',
    'no-unused-expressions': [
      'warn',
      {
        allowShortCircuit: true,
        allowTernary: true,
        allowTaggedTemplates: true,
      },
    ],
    'no-use-before-define': [
      'warn',
      {
        functions: false,
        classes: true,
        variables: true,
      },
    ],
    'no-useless-computed-key': 'warn',
    'no-useless-concat': 'warn',
    'no-useless-constructor': 'warn',
    'no-useless-rename': [
      'warn',
      {
        ignoreDestructuring: false,
        ignoreImport: false,
        ignoreExport: false,
      },
    ],
    'no-whitespace-before-property': 'warn',
    'rest-spread-spacing': ['warn', 'never'],
    strict: ['warn', 'never'],
    'unicode-bom': ['warn', 'never'],
    'no-restricted-properties': [
      'warn',
      {
        object: 'require',
        property: 'ensure',
        message:
          'Please use import() instead. More info: https://facebook.github.io/create-react-app/docs/code-splitting',
      },
      {
        object: 'System',
        property: 'import',
        message:
          'Please use import() instead. More info: https://facebook.github.io/create-react-app/docs/code-splitting',
      },
    ],
    'getter-return': 'warn',

    // PLUGINS
    // to use a rule from a plugin please add and load them first in EslintPluginRules

    // https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules
    'react/forbid-foreign-prop-types': ['warn', { allowInPropTypes: true }],
    'react/jsx-no-comment-textnodes': 'warn',
    'react/jsx-no-duplicate-props': 'warn',
    'react/jsx-no-target-blank': 'warn',
    'react/jsx-no-undef': 'warn',
    'react/jsx-pascal-case': [
      'warn',
      {
        allowAllCaps: true,
        ignore: [],
      },
    ],
    'react/jsx-uses-vars': 'warn',
    'react/no-danger-with-children': 'warn',
    'react/no-deprecated': 'warn',
    'react/no-direct-mutation-state': 'warn',
    'react/no-is-mounted': 'warn',
    'react/no-typos': 'warn',
    'react/require-render-return': 'warn',
    'react/style-prop-object': 'warn',

    // https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks
    'react-hooks/exhaustive-deps': 'warn',
    'react-hooks/rules-of-hooks': 'warn',

    // https://github.com/benmosher/eslint-plugin-import/tree/master/docs/rules
    'import/first': 'warn',
    'import/no-amd': 'warn',
    'import/no-webpack-loader-syntax': 'error',

    // https://github.com/evcohen/eslint-plugin-jsx-a11y/tree/master/docs/rules
    'jsx-a11y/accessible-emoji': 'warn',
    'jsx-a11y/alt-text': 'warn',
    'jsx-a11y/anchor-has-content': 'warn',
    'jsx-a11y/anchor-is-valid': [
      'warn',
      {
        aspects: ['noHref', 'invalidHref'],
      },
    ],
    'jsx-a11y/aria-activedescendant-has-tabindex': 'warn',
    'jsx-a11y/aria-props': 'warn',
    'jsx-a11y/aria-proptypes': 'warn',
    'jsx-a11y/aria-role': ['warn', { ignoreNonDOM: true }],
    'jsx-a11y/aria-unsupported-elements': 'warn',
    'jsx-a11y/heading-has-content': 'warn',
    'jsx-a11y/iframe-has-title': 'warn',
    'jsx-a11y/img-redundant-alt': 'warn',
    'jsx-a11y/no-access-key': 'warn',
    'jsx-a11y/no-distracting-elements': 'warn',
    'jsx-a11y/no-redundant-roles': 'warn',
    'jsx-a11y/role-has-required-aria-props': 'warn',
    'jsx-a11y/role-supports-aria-props': 'warn',
    'jsx-a11y/scope': 'warn',
  },
  settings: {
    react: {
      version: '17.0.0-rc.1',
    },
  },
}

const EslintPluginReactRules = {
  'react/jsx-boolean-value': reactPluginRules['jsx-boolean-value'],
  'react/jsx-child-element-spacing': reactPluginRules['jsx-child-element-spacing'],
  'react/jsx-closing-bracket-location': reactPluginRules['jsx-closing-bracket-location'],
  'react/jsx-closing-tag-location': reactPluginRules['jsx-closing-tag-location'],
  'react/jsx-curly-brace-presence': reactPluginRules['jsx-curly-brace-presence'],
  'react/jsx-curly-newline': reactPluginRules['jsx-curly-newline'],
  'react/jsx-curly-spacing': reactPluginRules['jsx-curly-spacing'],
  'react/jsx-equals-spacing': reactPluginRules['jsx-equals-spacing'],
  'react/jsx-filename-extension': reactPluginRules['jsx-filename-extension'],
  'react/jsx-first-prop-new-line': reactPluginRules['jsx-first-prop-new-line'],
  'react/jsx-fragments': reactPluginRules['jsx-fragments'],
  'react/jsx-handler-names': reactPluginRules['jsx-handler-names'],
  'react/jsx-indent': reactPluginRules['jsx-indent'],
  'react/jsx-indent-props': reactPluginRules['jsx-indent-props'],
  'react/jsx-key': reactPluginRules['jsx-key'],
  'react/jsx-max-depth': reactPluginRules['jsx-max-depth'],
  'react/jsx-max-props-per-line': reactPluginRules['jsx-max-props-per-line'],
  'react/jsx-no-bind': reactPluginRules['jsx-no-bind'],
  'react/jsx-no-comment-textnodes': reactPluginRules['jsx-no-comment-textnodes'],
  'react/jsx-no-duplicate-props': reactPluginRules['jsx-no-duplicate-props'],
  'react/jsx-no-literals': reactPluginRules['jsx-no-literals'],
  'react/jsx-no-script-url': reactPluginRules['jsx-no-script-url'],
  'react/jsx-no-target-blank': reactPluginRules['jsx-no-target-blank'],
  'react/jsx-no-undef': reactPluginRules['jsx-no-undef'],
  'react/jsx-no-useless-fragment': reactPluginRules['jsx-no-useless-fragment'],
  'react/jsx-one-expression-per-line': reactPluginRules['jsx-one-expression-per-line'],
  'react/jsx-pascal-case': reactPluginRules['jsx-pascal-case'],
  'react/jsx-props-no-multi-spaces': reactPluginRules['jsx-props-no-multi-spaces'],
  'react/jsx-props-no-spreading': reactPluginRules['jsx-props-no-spreading'],
  'react/jsx-sort-default-props': reactPluginRules['jsx-sort-default-props'],
  'react/jsx-sort-props': reactPluginRules['jsx-sort-props'],
  'react/jsx-space-before-closing': reactPluginRules['jsx-space-before-closing'],
  'react/jsx-tag-spacing': reactPluginRules['jsx-tag-spacing'],
  'react/jsx-uses-vars': reactPluginRules['jsx-uses-vars'],
  'react/jsx-wrap-multilines': reactPluginRules['jsx-wrap-multilines'],
  'react/boolean-prop-naming': reactPluginRules['boolean-prop-naming'],
  'react/button-has-type': reactPluginRules['button-has-type'],
  'react/default-props-match-prop-types': reactPluginRules['default-props-match-prop-types'],
  'react/destructuring-assignment': reactPluginRules['destructuring-assignment'],
  'react/display-name': reactPluginRules['display-name'],
  'react/forbid-component-props': reactPluginRules['forbid-component-props'],
  'react/forbid-dom-props': reactPluginRules['forbid-dom-props'],
  'react/forbid-elements': reactPluginRules['forbid-elements'],
  'react/forbid-foreign-prop-types': reactPluginRules['forbid-foreign-prop-types'],
  'react/forbid-prop-types': reactPluginRules['forbid-prop-types'],
  'react/function-component-definition': reactPluginRules['function-component-definition'],
  'react/no-access-state-in-setstate': reactPluginRules['no-access-state-in-setstate'],
  'react/no-adjacent-inline-elements': reactPluginRules['no-adjacent-inline-elements'],
  'react/no-array-index-key': reactPluginRules['no-array-index-key'],
  'react/no-children-prop': reactPluginRules['no-children-prop'],
  'react/no-danger': reactPluginRules['no-danger'],
  'react/no-danger-with-children': reactPluginRules['no-danger-with-children'],
  'react/no-deprecated': reactPluginRules['no-deprecated'],
  'react/no-did-mount-set-state': reactPluginRules['no-did-mount-set-state'],
  'react/no-did-update-set-state': reactPluginRules['no-did-update-set-state'],
  'react/no-direct-mutation-state': reactPluginRules['no-direct-mutation-state'],
  'react/no-find-dom-node': reactPluginRules['no-find-dom-node'],
  'react/no-is-mounted': reactPluginRules['no-is-mounted'],
  'react/no-multi-comp': reactPluginRules['no-multi-comp'],
  'react/no-redundant-should-component-update':
    reactPluginRules['no-redundant-should-component-update'],
  'react/no-render-return-value': reactPluginRules['no-render-return-value'],
  'react/no-set-state': reactPluginRules['no-set-state'],
  'react/no-string-refs': reactPluginRules['no-string-refs'],
  'react/no-this-in-sfc': reactPluginRules['no-this-in-sfc'],
  'react/no-typos': reactPluginRules['no-typos'],
  'react/no-unescaped-entities': reactPluginRules['no-unescaped-entities'],
  'react/no-unknown-property': reactPluginRules['no-unknown-property'],
  'react/no-unsafe': reactPluginRules['no-unsafe'],
  'react/no-unused-prop-types': reactPluginRules['no-unused-prop-types'],
  'react/no-unused-state': reactPluginRules['no-unused-state'],
  'react/no-will-update-set-state': reactPluginRules['no-will-update-set-state'],
  'react/prefer-es6-class': reactPluginRules['prefer-es6-class'],
  'react/prefer-read-only-props': reactPluginRules['prefer-read-only-props'],
  'react/prefer-stateless-function': reactPluginRules['prefer-stateless-function'],
  'react/prop-types': reactPluginRules['prop-types'],
  'react/require-default-props': reactPluginRules['require-default-props'],
  'react/require-optimization': reactPluginRules['require-optimization'],
  'react/require-render-return': reactPluginRules['require-render-return'],
  'react/self-closing-comp': reactPluginRules['self-closing-comp'],
  'react/sort-comp': reactPluginRules['sort-comp'],
  'react/sort-prop-types': reactPluginRules['sort-prop-types'],
  'react/state-in-constructor': reactPluginRules['state-in-constructor'],
  'react/static-property-placement': reactPluginRules['static-property-placement'],
  'react/style-prop-object': reactPluginRules['style-prop-object'],
  'react/void-dom-elements-no-children': reactPluginRules['void-dom-elements-no-children'],
}

const EslintPluginReactHooksRules = {
  'react-hooks/exhaustive-deps': reactHooksPluginRules['exhaustive-deps'],
  'react-hooks/rules-of-hooks': reactHooksPluginRules['rules-of-hooks'],
}

const EslintPluginImportRules = {
  'import/first': eslintImportRuleFirst,
  'import/no-amd': eslintImportRuleNoAmd,
  'import/no-webpack-loader-syntax': eslintImportRuleNoWebpackSyntax,
}

const EslintPluginJsxA11yRules = {
  'jsx-a11y/accessible-emoji': jsxA11yPluginRules['accessible-emoji'],
  'jsx-a11y/alt-text': jsxA11yPluginRules['alt-text'],
  'jsx-a11y/anchor-has-content': jsxA11yPluginRules['anchor-has-content'],
  'jsx-a11y/anchor-is-valid': jsxA11yPluginRules['anchor-is-valid'],
  'jsx-a11y/aria-activedescendant-has-tabindex':
    jsxA11yPluginRules['aria-activedescendant-has-tabindex'],
  'jsx-a11y/aria-props': jsxA11yPluginRules['aria-props'],
  'jsx-a11y/aria-proptypes': jsxA11yPluginRules['aria-proptypes'],
  'jsx-a11y/aria-role': jsxA11yPluginRules['aria-role'],
  'jsx-a11y/aria-unsupported-elements': jsxA11yPluginRules['aria-unsupported-elements'],
  'jsx-a11y/heading-has-content': jsxA11yPluginRules['heading-has-content'],
  'jsx-a11y/iframe-has-title': jsxA11yPluginRules['iframe-has-title'],
  'jsx-a11y/img-redundant-alt': jsxA11yPluginRules['img-redundant-alt'],
  'jsx-a11y/no-access-key': jsxA11yPluginRules['no-access-key'],
  'jsx-a11y/no-distracting-elements': jsxA11yPluginRules['no-distracting-elements'],
  'jsx-a11y/no-redundant-roles': jsxA11yPluginRules['no-redundant-roles'],
  'jsx-a11y/role-has-required-aria-props': jsxA11yPluginRules['role-has-required-aria-props'],
  'jsx-a11y/role-supports-aria-props': jsxA11yPluginRules['role-supports-aria-props'],
  'jsx-a11y/scope': jsxA11yPluginRules['scope'],
}

export const EslintPluginRules = {
  ...EslintPluginReactRules,
  ...EslintPluginReactHooksRules,
  ...EslintPluginImportRules,
  ...EslintPluginJsxA11yRules,
}
