import { ReactDOM } from 'react'
import { canvasRectangle, CanvasRectangle, scaleRect } from './math-utils'
import { replaceAll } from './string-utils'

export const intrinsicHTMLElementNames: Array<keyof ReactDOM> = [
  'a',
  'abbr',
  'address',
  'area',
  'article',
  'aside',
  'audio',
  'b',
  'base',
  'bdi',
  'bdo',
  'big',
  'blockquote',
  'body',
  'br',
  'button',
  'canvas',
  'caption',
  'cite',
  'code',
  'col',
  'colgroup',
  'data',
  'datalist',
  'dd',
  'del',
  'details',
  'dfn',
  'dialog',
  'div',
  'dl',
  'dt',
  'em',
  'embed',
  'fieldset',
  'figcaption',
  'figure',
  'footer',
  'form',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'head',
  'header',
  'hgroup',
  'hr',
  'html',
  'i',
  'iframe',
  'img',
  'input',
  'ins',
  'kbd',
  'keygen',
  'label',
  'legend',
  'li',
  'link',
  'main',
  'map',
  'mark',
  'menu',
  'menuitem',
  'meta',
  'meter',
  'nav',
  'noscript',
  'object',
  'ol',
  'optgroup',
  'option',
  'output',
  'p',
  'param',
  'picture',
  'pre',
  'progress',
  'q',
  'rp',
  'rt',
  'ruby',
  's',
  'samp',
  'script',
  'section',
  'select',
  'small',
  'source',
  'span',
  'strong',
  'style',
  'sub',
  'summary',
  'sup',
  'table',
  'template',
  'tbody',
  'td',
  'textarea',
  'tfoot',
  'th',
  'thead',
  'time',
  'title',
  'tr',
  'track',
  'u',
  'ul',
  'video',
  'wbr',
  'webview',
  'animate',
  'circle',
  'clipPath',
  'defs',
  'desc',
  'ellipse',
  'feBlend',
  'feColorMatrix',
  'feComponentTransfer',
  'feComposite',
  'feConvolveMatrix',
  'feDiffuseLighting',
  'feDisplacementMap',
  'feDistantLight',
  'feDropShadow',
  'feFlood',
  'feFuncA',
  'feFuncB',
  'feFuncG',
  'feFuncR',
  'feGaussianBlur',
  'feImage',
  'feMerge',
  'feMergeNode',
  'feMorphology',
  'feOffset',
  'fePointLight',
  'feSpecularLighting',
  'feSpotLight',
  'feTile',
  'feTurbulence',
  'filter',
  'foreignObject',
  'g',
  'image',
  'line',
  'linearGradient',
  'marker',
  'mask',
  'metadata',
  'path',
  'pattern',
  'polygon',
  'polyline',
  'radialGradient',
  'rect',
  'stop',
  'svg',
  'switch',
  'symbol',
  'text',
  'textPath',
  'tspan',
  'use',
  'view',
]

export const intrinsicHTMLElementNamesAsStrings: Array<string> = intrinsicHTMLElementNames
export const intrinsicHTMLElementNamesThatSupportChildren: Array<string> = [
  // Based on a elements from https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Flow_content
  // which also supports flow content
  'a',
  'address',
  'article',
  'aside',
  'b',
  'bdo',
  'bdi',
  'blockquote',
  'button',
  'details',
  'dfn',
  'div',
  'dl',
  'fieldset',
  'figure',
  'footer',
  'form',
  'header',
  'main',
  'menu',
  'nav',
  'section',
]

export function getCanvasRectangleFromElement(
  element: Element,
  canvasScale: number,
): CanvasRectangle {
  const boundingRect = element.getBoundingClientRect()

  // canvas container uses scale for <1 zoom level, it should not affect the frame of the element.
  const scale = canvasScale < 1 ? 1 / canvasScale : 1
  return scaleRect(
    canvasRectangle({
      x: boundingRect.left,
      y: boundingRect.top,
      width: boundingRect.width,
      height: boundingRect.height,
    }),
    scale,
  )
}

export function urlSafeText(text: string): string {
  return encodeURIComponent(replaceAll(text.toLowerCase(), ' ', '-'))
}
