name: Discord Integration - PR Review
on:
  pull_request_review:
    types: [submitted]

jobs:
  post-to-discord:
    name: Post Notification To Discord
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Build Partial Embeds JSON
        env:
          TEMPLATE: >-
            [{
              "title": "$review_status #$pull_request_number $title",
              "color": $color,
              "url": $html_url,
              "footer": {
                "text": "$sender_name | $repo_full_name",
                "icon_url": $sender_avatar
              }
            }]
          PR_NUMBER: ${{ github.event.pull_request.number }}
          TITLE: ${{ github.event.pull_request.title }}
          HTML_URL: ${{ github.event.review.html_url }}
          SENDER_NAME: ${{ github.event.sender.login }}
          SENDER_AVATAR: ${{ github.event.sender.avatar_url }}
          REPO_FULL_NAME: ${{ github.event.repository.full_name }}
        run: |
          echo "PARTIAL_EMBEDS=$(jq -nc --arg pull_request_number "$PR_NUMBER" --arg title "$TITLE" --arg html_url "$HTML_URL" --arg sender_name "$SENDER_NAME" --arg sender_avatar "$SENDER_AVATAR" --arg repo_full_name "$REPO_FULL_NAME" "$TEMPLATE")" >> $GITHUB_ENV
      - name: Build Approval Embeds JSON
        if: ${{ github.event.review.state == 'approved' }}
        env:
          SENDER_NAME: ${{ github.event.sender.login }}
        run: |
          echo "DISCORD_EMBEDS=$(jq -nc --arg review_status "Approved" --arg color "3581519" "$PARTIAL_EMBEDS")" >> $GITHUB_ENV
          echo "MESSAGE_ARGS='PR approved by $SENDER_NAME'" >> $GITHUB_ENV
      - name: Build Changes Requested Embeds JSON
        if: ${{ github.event.review.state == 'changes_requested' }}
        env:
          SENDER_NAME: ${{ github.event.sender.login }}
        run: |
          echo "DISCORD_EMBEDS=$(jq -nc --arg review_status "Changes Requested" --arg color "13313073" "$PARTIAL_EMBEDS")" >> $GITHUB_ENV
          echo "MESSAGE_ARGS='Changes requested by $SENDER_NAME'" >> $GITHUB_ENV
      - name: Send Notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_PRS_WEBHOOK }}
          DISCORD_USERNAME: 'GitHub'
          DISCORD_AVATAR: https://octodex.github.com/images/inspectocat.jpg
        with:
          args: ${{ env.MESSAGE_ARGS }}
