name: Discord Integration - PR Review
on:
  pull_request_review:
    types: [submitted]

jobs:
  post-to-discord:
    name: Post Notification To Discord
    runs-on: ubuntu-latest
    if: ${{ github.event.review.state == 'approved' || github.event.review.state == 'changes_requested' }}
    steps:
      - name: Build Approval Args
        if: ${{ github.event.review.state == 'approved' }}
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          SENDER_NAME: ${{ github.event.sender.login }}
        run: |
          echo "TITLE=Approved #$PR_NUMBER $PR_TITLE" >> $GITHUB_ENV
          echo "COLOR=3581519" >> $GITHUB_ENV
          echo "MESSAGE_ARGS=PR approved by $SENDER_NAME" >> $GITHUB_ENV
      - name: Build Changes Requested Args
        if: ${{ github.event.review.state == 'changes_requested' }}
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          SENDER_NAME: ${{ github.event.sender.login }}
        run: |
          echo "TITLE=Changes Requested #$PR_NUMBER $PR_TITLE" >> $GITHUB_ENV
          echo "COLOR=13313073" >> $GITHUB_ENV
          echo "MESSAGE_ARGS=Changes requested by $SENDER_NAME" >> $GITHUB_ENV
      - name: Build Embeds JSON
        env:
          TEMPLATE: >-
            [{
              "title": $title,
              "color": $color,
              "url": $html_url,
              "footer": {
                "text": $sender_name,
                "icon_url": $sender_avatar
              }
            }]
          HTML_URL: ${{ github.event.review.html_url }}
          SENDER_NAME: ${{ github.event.sender.login }}
          SENDER_AVATAR: ${{ github.event.sender.avatar_url }}
        run: |
          echo "DISCORD_EMBEDS=$(jq -nc --arg --arg title "$TITLE" --arg color "$COLOR" --arg html_url "$HTML_URL" --arg sender_name "$SENDER_NAME" --arg sender_avatar "$SENDER_AVATAR" "$TEMPLATE")" >> $GITHUB_ENV
      - name: Send Notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_PRS_WEBHOOK }}
          DISCORD_USERNAME: 'GitHub'
          DISCORD_AVATAR: https://octodex.github.com/images/inspectocat.jpg
        with:
          args: ${{ env.MESSAGE_ARGS }}
