name: Google Webfonts Updater
on: [pull_request] # update me to crontab for every day
#on:
#  schedule:
#    - cron: "0 8 * * *" # run daily at 8.00am
jobs:
  google-web-fonts-updater:
    name: Google Web Fonts Updater
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }} # remove me
      - name: Get Google Fonts list file contents
        uses: ./.github/actions/get-google-fonts-list-file/
        id: get-google-fonts-list-file-contents
        env:
          GOOGLE_WEB_FONTS_KEY: ${{secrets.GOOGLE_WEB_FONTS_KEY}}
      - name: Write to file
        run: echo "${{ steps.get-google-fonts-list-file-contents.outputs.google-fonts-file }}" > $GITHUB_WORKSPACE/editor/assets/google-fonts-list.ts
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.1.0
        with:
          title: 'Update Google Fonts list (${{steps.get-google-fonts-list-file-contents.outputs.google-fonts-list-length}} fonts)'
          token: ${{secrets.GOOGLE_FONTS_AUTOUPDATER_PAT}}
          commit-message: Update google fonts list (${{steps.get-google-fonts-list-file-contents.outputs.google-fonts-list-length}} fonts)
          branch: chore/update-google-fonts-list
          labels: |
            automated pr
          reviewers: |
            alecmolloy
            balazsbajorics
            enidemi
            Rheeseyb
            seanparsons
          body: T̴̨̢͕̳͉̹̠͚̘̥͍͎͎̭̜̎̀̌̌͝ḩ̶̱̪̯̤̤̤̺̪͈͚͓̖́̍͒̔́͂̀̕͝ḛ̷̛͎͓͖̬̫͈̠͚̞̿̿͆͜͝ ̸̯̲͙̪̼͕̜̞̰͖͕͉̯͓́̈̍́̐̈̌̕̕̚͜͝͠F̵̢͍̠͔̼̝͚͓̮̖̑̿͐̈́̂̿̃͑̇̊̿̐͠o̶͚̮̖͇̩̮̼̐͜r̷̡͉̱̫̤̤̼̤̎b̶̧̪̮͛͒̐͑̉̀̿̈́͂̍͜i̴̦͓̟̺͖͍̺͌̀͌̾͊͋͘͘͠͠d̵̨̨̹̩̯̊͒̀̔͌͋͜ḏ̸̱̖̥̪̪̙̝̞̣̬̔̍͗̈́̾̉͊̍̉́̈́͘͠͝͠ę̴̡̨͓̹͈̻͔̪̼̘͚̳̉̑̂̑̋̑̕̚͜ͅṅ̷̛͍̥͚̙̳͐̀̐̌̓͋͆͑̓̓̚͠ ̸̨̫̱̤̼̜̘͇̝͈̼̥̠̭̻͂̄̈́͌̋͆̀͠͝S̴̛̬̘̜̹̩̱̬̈́͑̏̎͒̈́m̵̢̢̨̯̰̠̳̖͔̣̣͚̺̓͌̔͗̇͌̐̇̽̚y̸̢̢͖̞̙͓͎͍̻͎͚̬̠̝̅̄̀͘r̴̨̢̺̘͍̫͇̗̤̭̻͚̈̓̉̚͜ą̴̦͚̥͉̺̱͂̿̌̈́͌͒̒͛̚͘m̴̛͉̩̗͖̙̟̀̊̈́̍̈̅̄̽̚ĩ̴̢̼͉̄̐̐̓̈́̌̀̊̒̋̓̌̍͠d̸̛̙̰̳̣͑͌̿̈́̆̿̏̊̾̚ ̴̧̢̛͕̲̬̤͈͓̭̳̬̪̼͓̩̎̔͗̿̌͋̂̀͐͗̏͛̊̚d̴̨̯̂͝e̵̯̋m̴͎͚̓̃̄a̴̧͖͇͎͍͚͖̙̗̥̔̉̓͗̅̄̉̕͘͝ṋ̶̂̽͒́͒͗̐̀͝͠d̸̗̬̮͈̳͙̈́̎̔̀̉͆̈̈́̚͝͝s̴̨̡̧̟͙̩̪̙̻̦̤͈̮̗̄̐̾͒͑͜ ̷̨̰̘̬̺̯̞͙̫̠͈̻̹̞̥̔̆̒̌̄͑̈͛̍͒͆̉̀̕͠y̶̧̻̜̘͙͂͛̍̆̒͑̐̿̃̑͘͠o̵̤͈̗̖̭̹̼̫̬̤͙͒̈́̌̈́͂̽̈́̈́̉́́͝ͅṷ̷̧̳̲͖̳̹̱̻̺̼̖̈́̌́̀̅̅̽͒̑͌͆͜ͅͅ ̶̜̖̞̳̼̱̆̂̽̐̈́̈̈̋̀̒̐̔͌̕͘u̴̻͉̭͖̣̦̩̲͕̙͖̤̼̥̚̕͜ṕ̸̧͔̺̥͕̟̽̋̀̽̋d̴͔̲̀͌̉̀͊̂̃͋̈́̏͊̓̐̕͝ą̷̧̗̞̤̹̠͖̻̤̭̏́̿͂͆͒́͊̉̃̌̈́̚ț̵̨̛̯̫̗͇̈́̈̍͂̀͝͠ͅḛ̴̢͎͎͕̯̺͍̪͔̺̰̬̞͎̒̍̔̐͛̆̄̑̊̀ ̸̢̨̨̡̪͇͉̜̣̯͍͚͗̋͐͗̊̑̕͝T̴̗̝̙̰͍̭͍̜͚̖̿͗̑̐͗̇̊̉́H̴̡̡̯̃E̵̹̗̩͛̎͆́̃̍̆͂́̏͘ ̵̬̻͗̀̂͌͝F̵̨̯̳͙́̈Ŏ̷̧̢̼̝͉̳̗̪̰͈͍̼̾̓̾̈́̓̒̕͜͠ͅŃ̴̜̥̳̱͕̖͖͍̤̟̤̈́́̈́̽̿̃̄̃̑̀̕̕T̸̗͌̍Š̷̢̡̮̦̮̤̻̳͔̣̱̤͙̣̾͐́̄̋̈́́̎̋̚̕<img width="143" alt="Ḩ̷̡̡͎̙̯̤̬̺̹̥̲͍̤͇̬͙̣̥̹̥̝͓̙̳̟̟̺̿͆̈́͋̓́̅̉͒̇́̑͊͗̽̄̔̄͑͐̓̃̇̚̚͘͘̚͘͝͝ą̸̢̨̧̞͎̺͖̫͇̦̦̰̤̘̭̾̉̍͌̾͊̀̿͛͛̆̓͋̽̑̈́̽̋̈́͛̕̚͝͠v̶̡̢̨̡̛̛̛̠̗̯̳͇̱̱̲̹͇̦̮̻̞̲̰̗̮̪̟̫̝̮̈́͋̇͗́̏̀͋͗̔̈́̊̔̍̕͘͝͠ͅe̶̡̡̢̢̢̨̡̧͔̯͔̪̬̮̥̗͔͎̯͕̠͙̥̠̖̤͖̜͌́̂͊̋̎̂̋͐̀͑̿̊̚͠ ̷̢̧̛̦̟͈͎̹̻̞͙̭͇̦̗̞͓̭̺͓̭̓̓̀̌̑̇͋̅̎̀̐̑̐̇͂͆̓̐̈͒̏̿̃̓̕̚͘̕͠m̴͇͇̫̥̹͔̼̣͔̦͍̳̞̯͌͌̈̈͐̅͋͌̇͗͌̋̊̌̒̈́̌̉͌̀̇̃̈́̽͂̓̃͐̄̎̈́̕͜͜͜ͅȩ̵̨͚͈̻̞̞̜̒́͐̿̾͐͐̎͑́͆͠r̵̨̡̡̧̡̛̛̜̟̹̥̜̯̗̟͖͈͔̪̗̺̯̙̳̲͓̺̙͙͔͚̯͕͎̤̈́̅̈͠c̵̨̢̢̛̬͉͖̰͍̟͙̖̲̗̫̻͔͗̋͌̃͑͐͒̑̀̒̈́̔̓̊̆̂͂͝y̸̺̥̣̙̼̟̲̼̣̣̗͚͍̰̤̹̜̩̝͕̱̤͕̘̮͍̤͗͐͋͐̈́͒̅͛̐͗͘ͅ ̶̫̗̳͔̔͗̽̉̀̐̀̃̑̀̀̑̊̄͌̋̈͋͛͐̀̃̍̃̕͘̚͠ͅơ̶̢̟͓̪͖̞̯̯̩̞̣̹̎̌͆̅̂̒̓̐͊̽̽̎͆͋̐̄͛̈͠͠͝n̷̫͔͇̦̙͓͍̲̖̳̫͖͍̯̬͊̎̾̃͒̇̏̆̐͛̎̌͒̒͂̃̀̊̒̓̋͂͋͆͆̀̀͒͆̄̋̏͘͠͝͠ ̶̢̛̛͕̪̙͈͓̑̄̿͛͛͛́̐̄̈͑̏͐̔͊̉̎̈́́̊́͆̒̀̚͘m̶̧̬̤̺͚̩͇͓̱̞̤̳̩͓̬͔̲̮̳̬̺̗̤̝̪͈͖̟͗͌̔͌̈̔̄̌̆́͆̾̏̀̈́͆͑͑͠͝͠ͅͅͅe̵̡̗̱̫̯̩͛̋̈́̊̒̌̍̈́̒͐̌̎͐̇̄̀͊́̃̈́̒̆͑͆̓͋́͋͘ ̵̧̡͚̟̯̳̪͔̰̹̗̼̠͕͍̖̪͉̹͚̺̒̓͛͌͂̍̿̾̉̒͒͋͋͗͛̾̀̊̈́͆͌̇̊̂̽̕͘͝ö̶̧̡̪̥͔͚͎̭̖̠͙̗̰̘̝̲̠̠̩͉͔͙̼́̆̿̔̋̑͗̀͆̓̄̕͜͜ḩ̴͍̻̩͕̘̭̘̭̫̙̹́̈̓ ̸̧̭̠̜̥̫̯̗͊͛̊̉̋̂̈̀͑́̀͛̏̎̅̅̌͂̄̈́̇͋̈́̄̒̄̀̾͘̚͘͝F̵̧̡̥̰̼͙̮̟̘̙͖̻̜̘̺͇̘͐̍̌̓̇̄̀̔̀̔̄̓̾̋͗̋̚ͅo̵̧̙̬̪̓͛͂͐͑̈̋̐͑͗̀̚͝ṟ̵̡̢̧̢̛̛̩̰͈̹̮̥͕͈̠̞͖͈̪̹̣̰̠̘̙̙̩͍̩̝͉̰͓̗͖̾̊̾́̾̈́͒̊͋̓̌̿̎͛̚̚͜͜͠b̷̡̢̢̨̻͔͖̥̟̲̼̮̗̼̖̻͇͇̰̲͎̟͍̻̝̣͚͆̊̑͑̇͛̐̊̓͜͝͝ĭ̸̻͇̖̻̤̅͊̅d̷̛͇̙̯̻̘̣̞̗͍̯̮̪̭̲̦̦͇̣̱͎̖͎̝̦̣̝̝̯̖̱̼̖̔̐̇̎̒͛͊̈́̌͊̑͌̃̽̊̒̄̌̕̚͠͠ͅd̴̢̲̰͕̟̤̝̻̫̬̗̲͓̮̞̳̯̱̩̩̰̰͖̤̩̩͚̩͇́̃̍̀̏̃̎̈́̉̊͜͜͜͝ę̶̢̨̛̜͇̱̟͍͖̻͗̈ͅn̷̨̬̩̻͚͉̬̏̂̂̽̓̈̑̊̅̒͋͝ ̵͕͈̗̝͓͎̠̩̺͖͇̮̜͌Ȍ̶̧̨̡͕̱͙͍̻͕̲̣̞̪͕̱̱͕͎̦̬͈͎͇̜̤̰͔͈͔͕̝͕͜n̶̨̧̥̠̣̝̪̘̯͓͎̮̰͍͉̣̥͓̞̠̭̽̀́͌́̽̐̿̓̍̎̓̅̏̀͐̄͘͘͜͝e̸̛̞̝̮͍̩͎̹̘̻̋̒̔͒̆̆̍́̌̒͋̆̀̄͒͌̀̈́̓́̽͑̀̓̈́͘͜" src="https://user-images.githubusercontent.com/4676536/90292182-4b3b5000-de36-11ea-9135-278d0669e9e0.png">
