name: Google Webfonts Updater
on:
  schedule:
    - cron: '0 8 * * *' # run daily at 8.00am
jobs:
  google-web-fonts-updater:
    name: Google Web Fonts Updater
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: Get Google Fonts list file contents
        uses: ./.github/actions/get-google-fonts-list-file/
        id: get-google-fonts-list-file-contents
        env:
          GOOGLE_WEB_FONTS_KEY: ${{secrets.GOOGLE_WEB_FONTS_KEY}}
      - name: Write to file
        run: echo "${{ steps.get-google-fonts-list-file-contents.outputs.google-fonts-file }}" > $GITHUB_WORKSPACE/editor/assets/google-fonts-list.ts
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.1.0
        with:
          title: '∆ Update The Fonts (${{steps.get-google-fonts-list-file-contents.outputs.google-fonts-list-length}} fonts) ⟁'
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: GitHub <noreply@github.com>
          token: ${{secrets.GITHUB_TOKEN}}
          commit-message: Update google fonts list (${{steps.get-google-fonts-list-file-contents.outputs.google-fonts-list-length}} fonts)
          branch: chore/update-google-fonts-list
          labels: |
            automated pr
          reviewers: |
            alecmolloy
            balazsbajorics
            enidemi
            Rheeseyb
            seanparsons
          body: |
            The Forbidden One requests you update your list of available google fonts.
            <img width="143" title="The Forbidden One is pleased… for now" src="https://user-images.githubusercontent.com/4676536/90292182-4b3b5000-de36-11ea-9135-278d0669e9e0.png">
