name: Google Webfonts Updater
on: [pull_request] # update me to crontab for every day
#on:
#  schedule:
#    - cron: "0 8 * * *" # run daily at 8.00am
jobs:
  google-web-fonts-updater:
    name: Google Web Fonts Updater
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }} # remove me
      - name: Get Google Fonts list file contents
        uses: ./.github/actions/get-google-fonts-list-file/
        id: get-google-fonts-list-file-contents
      - name: Write to file
        env: ${{secrets.GOOGLE_WEB_FONTS_KEY}}
        run: echo "${{ steps.get-google-fonts-list-file-contents.outputs.google-fonts-file }}" > $GITHUB_WORKSPACE/editor/assets/google-fonts-list.ts
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.1.0
        with:
          committer: The Forbidden Smyramid <forbidden-smyramid@utopia.app>
          token: ${{secrets.GOOGLE_FONTS_AUTOUPDATER_PAT}}
          commit-message: Update google fonts list (${{steps.get-google-fonts-list-file-contents.outputs.google-fonts-list-length}} fonts)
          branch: chore/update-google-fonts-list
          title: 'Update Google Fonts list (${{steps.get-google-fonts-list-file-contents.outputs.google-fonts-list-length}} fonts)'
          body: Auto-generated by google-web-fonts-updater
          labels: |
            automated pr
          reviewers: |
            alecmolloy
            balazsbajorics
            enidemi
            Rheeseyb
            seanparsons
