name: Test Common Workflow
on:
  workflow_call:

jobs:
  log-the-input:
    name: Log the input
    runs-on: ubuntu-latest
    steps:
      - name: Log it
        run: echo "Secret was defined? ${{ secrets.DEPLOY_REPO_ACCESS_TOKEN != null }}"
